### ISSUE TITLE
v2.6.1 CachedInputFileSystem error 

### ISSUE THREAD

**Issue by webyonet** [webpack/webpack-dev-server#1005]
if watch is enabled in webpack config:

```
/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145
			if(key.startsWith(what))
			      ^

TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:145:10)
    at Storage.purge (/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:150:9)
    at CachedInputFileSystem.purge (/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:20)
    at EventEmitter.watcher.once (/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/webpack/lib/node/NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (/Users/burak.demirezen/Documents/Projects/widget-v3-configurator/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! broadage-widget-v3-configurator@1.0.0 deploy-dev: `webpack --config webpack-dev.config.js --colors --progress --profile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the broadage-widget-v3-configurator@1.0.0 deploy-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/burak.demirezen/.npm/_logs/2017-07-24T08_53_53_623Z-debug.log
```

**Comment by webyonet** [comment]
sory this problem is only in the webpack v3.0.0

**Comment by Alex-Sokolov** [comment]
@webyonet how you solve it?
Works for me with webpack 3.3.0 & webpack-dev-server 2.5.1
Crashed with webpack 3.3.0 & webpack-dev-server 2.6.1

**Comment by AleshaOleg** [comment]
Why this issue closed? I have similar error, with v3.3.0

**Comment by AleshaOleg** [comment]
@Alex-Sokolov you mentioned before, that it works with 2.5.1. Is it true? If yes, could you show me your webpack config?

**Comment by Alex-Sokolov** [comment]
@AleshaOleg  No, crashed also. Builded ok, but when hot reload start crashed

**Comment by AleshaOleg** [comment]
@Alex-Sokolov, same. Do you know, on which versions it will run now? I tried webpack@2.7.0 now, it also crashed

**Comment by coockoo** [comment]
Yea, this issue has been closed too soon. Experiencing the same result here.

**Comment by AleshaOleg** [comment]
Here is solution: https://github.com/webpack/enhanced-resolve/issues/97

**Comment by webyonet** [comment]
@AleshaOleg I have not solved the problem. WebPack has already opened issue for the same problem

**Comment by AleshaOleg** [comment]
@webyonet you need reinstall `enhanced-resolve`, not `webpack` or `webpack-dev-server`.

**Comment by webyonet** [comment]
@AleshaOleg ok. thanks for helping

**Comment by coockoo** [comment]
Maybe someone knows how to downgrade `enhanced-resolve` to `3.3.0` with `yarn` (Assuming there is no dependency of `enhanced-resolve` in project, only `webpack`)

**Comment by webyonet** [comment]
@AleshaOleg @coockoo  the problem was solved in enhanced-resolve 3.3.0

**Comment by Alex-Sokolov** [comment]
Fixed in https://github.com/webpack/enhanced-resolve/releases/tag/v3.4.1

**Comment by the-architect** [comment]
Can confirm, upgrade to 3.4.1 works.

**Comment by AleshaOleg** [comment]
@Alex-Sokolov @the-architect thanks
