### ISSUE TITLE
Unexpected error from object-hash

### ISSUE THREAD

**Issue by DoumanAsh** [webpack/webpack-dev-server#1234]
* Operating System: Windows 10 x64
* Node Version: 9.3.0
* NPM Version:  5.5.1
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.9.5

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code
Source code https://github.com/DoumanAsh/cpp-tour/tree/with_lessons | branch `with_lessons`
Config: https://github.com/DoumanAsh/cpp-tour/blob/with_lessons/webpack.config.js

### Expected Behavior
No error as with normal builds

### Actual Behavior
Occasional error when starting server or updating JS files.
Unclear why it is affecting only JS files and why it is happening only when code is rebuilt in dev server.
My only clue is that it seems to be related to dynamic load from directory `lessons/`

```
ERROR in ./src/main.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView
    at Hash.update (internal/crypto/hash.js:53:11)
    at write (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:166:22)
    at Object._string (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:297:7)
    at Object._object (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:213:30)
    at Object.dispatch (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:184:30)
    at D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:242:18
    at Array.forEach (<anonymous>)
    at Object._object (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:238:21)
    at Object.dispatch (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:184:30)
    at D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:256:23
    at Array.forEach (<anonymous>)
    at Object._array (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:255:20)
    at Object._object (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:213:30)
    at Object.dispatch (D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:184:30)
    at D:\repos\js-code\cpp-tour\node_modules\object-hash\index.js:242:18
    at Array.forEach (<anonymous>)
 @ multi (webpack)-dev-server/client?http://localhost:3333 ./src/main.js
```

### For Bugs; How can we reproduce the behavior?

`npm start`  to run dev server.
Error may happen on start, if not try to update any JS file in `src/js/*js` or `src/main.js`

**Comment by shellscape** [comment]
@DoumanAsh thanks for the issue, but please note that `webpack-dev-server` doesn't appear anywhere in that call stack. if it's an intermittent issue you may want to take it up with the `object-hash` project instead. Without more information it's hard to tell where that error is originating. `webpack-dev-server` doesn't depend directly on that module, so I'm afraid it's likely not an issue with this module. We'll leave this one open a while in case you can provide more info, but without greater insight I'm afraid we can't debug this one for you.

**Comment by DoumanAsh** [comment]
Sorry it seemed logical for me as errors happening only when loading into dev server.
I suppose it would be better close if `object-hash` is not used by dev-server at all.

**Comment by shellscape** [comment]
Well it's not used _directly_, but that's not to say it might be used indirectly, through one of the dependencies. It's just hard knowing what that would be without more info.

**Comment by vundyalaavinash** [comment]
I have the same issue. @shellscape where you able to resolve this ?

**Comment by DoumanAsh** [comment]
@vundyalaavinash I created issue on `object-hash` but had no input https://github.com/puleos/object-hash/issues/61

**Comment by dontito94** [comment]
i got same issue when am doing table migration using sequelize db:migrate

internal/crypto/hash.js:53
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView
    at Hash.update (internal/crypto/hash.js:53:11)
    at sha1 (/home/dontito/NodeORMs/node_modules/mysql2/lib/auth_41.js:30:8)
    at Object.token [as calculateToken] (/home/dontito/NodeORMs/node_modules/mysql2/lib/auth_41.js:64:16)
    at new HandshakeResponse (/home/dontito/NodeORMs/node_modules/mysql2/lib/packets/handshake_response.js:28:24)
    at ClientHandshake.sendCredentials (/home/dontito/NodeORMs/node_modules/mysql2/lib/commands/client_handshake.js:51:27)
    at ClientHandshake.handshakeInit (/home/dontito/NodeORMs/node_modules/mysql2/lib/commands/client_handshake.js:142:10)
    at ClientHandshake.Command.execute (/home/dontito/NodeORMs/node_modules/mysql2/lib/commands/command.js:40:20)
    at Connection.handlePacket (/home/dontito/NodeORMs/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/dontito/NodeORMs/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/dontito/NodeORMs/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/dontito/NodeORMs/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:590:20)

**Comment by ChetanAudipudy** [comment]
@dontito94 I'm running into the same issue. Did you find out how to fix it?

**Comment by davidpelayo** [comment]
Same for me. @dontito94 any input on how to fix it?

**Comment by davidpelayo** [comment]
I figured it out by lookin at [this comment](https://github.com/webpack/webpack/issues/4072#issuecomment-274272573). I had something similar going on:

```js
export { default as ContextModule } from './modules/ContextModule';
```

when it had to be:

```js
export { default as ContextModule } from './ContextModule';
```

Apparently Webpack doesn't check if the file exists, then reads it, gets `null` or `undefined`, then feeds this non-existent value to the crypto hash generator and then explodes.

**Comment by abhirathore2006** [comment]
i have the similar issue, i was using  the re-exported module and deleted the actual file and as @davidpelayo said if actual file doesn't exist it will throw this error.  till this get fixed the solution would be

1.  check git diff for removed or moved files
2.  remove or modify their exports and imports.
