### ISSUE TITLE
Babel with webpack-dev-server crash

### ISSUE THREAD

**Issue by Kureev** [webpack/webpack-dev-server#129]
Hi all,

I'm using 
```javascript
require("babel/register");
```
to use .jsx with ES6 syntax. But if I'm trying to implement a webpack-dev-server to it - I got this stack trace:
```bash
> node server.js

/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:15
		var addrs = appendings.map(function(a) { return addr + a });
		                       ^
TypeError: undefined is not a function
    at Tapable.<anonymous> (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:15:26)
    at Tapable.applyPluginsParallelBailResult (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:143:14)
    at Tapable.<anonymous> (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:103:8)
    at Tapable.Resolver.forEachBail (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:196:3)
    at Tapable.doResolve (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:102:7)
    at Tapable.resolve (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:45:14)
    at Tapable.resolve (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:23:14)
    at Tapable.<anonymous> (/Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/lib/NormalModuleFactory.js:52:27)
    at /Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/async/lib/async.js:570:21
    at /Users/xamd/Projects/fflux-isomorphic-example/node_modules/webpack/node_modules/async/lib/async.js:249:17
```
Why?

**Comment by Kureev** [comment]
Sorry, fake alert. I though webpack config accepts regexps in resolve object like
```javascript
resolve: {
    extensions: /\.jsx?$/
}
```
but the only working way is to specify all extensions in array
```javascript
resolve: {
    extensions: ['.js', '.jsx']
}
```
