### ISSUE TITLE
webpack, docker, MacOS =  EADDRINUSE 0.0.0.0:19000

### ISSUE THREAD

**Issue by td234** [webpack/webpack-dev-server#1293]
* Operating System: MacOS 10.13.2
* Node Version: 9.4.0
* NPM Version: 5.6.0
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.11.1

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
const
	Path = require('path'),
	Webpack = require('webpack'),
	ExtractTextPlugin = require('extract-text-webpack-plugin'),

	// Create multiple instances
	extractCSS = new ExtractTextPlugin('styles-vendor.css'),
	extractSCSS = new ExtractTextPlugin('styles-bundle.css'),
	rootDir = Path.resolve(__dirname, '..', '..'),
	srcDir = Path.resolve(rootDir, 'src'),
	isProduction = process.env.NODE_ENV === 'production'

const config = {
	context: srcDir,
	entry: {
		vendor: [
			"./vendor"
		],
		bundle: [
			"./styles/root.scss",
			"./entry"
		]
	},
	output: {
		filename: "[name].js",
		path: Path.resolve(rootDir, 'dist', 'assets'),
		publicPath: "/assets/"
	},
	module: {
		rules: [{
			test: /\.jsx?$/,
			exclude: [/node_modules/],
			use: ['babel-loader']
		},
			// 	{
			// 	loader: ,
			// 	options: require(Path.resolve(rootDir,'.babelrc'))
			// },
			{
				test: /\.(jpg|png|gif|ttf|woff|woff2|otf|svg|eot)$/,
				use: [
					'file-loader'
				],
			}, {
				test: /\.css$/,
				use: extractCSS.extract([ 'css-loader'])
				// 	[
				// 	'style-loader',
				// 	'css-loader'
				// ],
			}, {
				test: /\.scss$/,
				use: extractSCSS.extract([ 'css-loader','sass-loader'])
				// use: [
				// 	'style-loader',
				// 	'css-loader',
				// 	'sass-loader'
				// ],
			}]
	},
	devtool: isProduction ? "source-map" : "inline-source-map",
	plugins: [
		// new Webpack.ProvidePlugin({
		// 	'Promise': 'bluebird'
		// }),
		extractCSS,
		extractSCSS,
		new Webpack.optimize.CommonsChunkPlugin({
			name: "vendor"
		})
	],
	node: {
		__filename: true,
		__dirname: true
	},
	devServer: {
		contentBase: Path.resolve(srcDir),
		publicPath: "/assets/",
		port: 19000,
		host: "0.0.0.0"
	}
	
}
if (isProduction) {
	config.plugins.unshift(
		new Webpack.optimize.UglifyJsPlugin({
			sourceMap: true,
			compress: {
				warnings: true,
				drop_console: false,
			}
		})
	)
}

module.exports = config
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior
npm run dev:start 
I expect this to start webpack-dev-server, but I am getting an error about the port being in use. I am running a docker container, so I suspect that suspect that I am opening and listening to that port when creating the docker container. What's on that port is this:

```
$ lsof -i tcp:19000
COMMAND PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vpnkit  604 thom   22u  IPv4 0x959c8f50c6647f33      0t0  TCP *:igrid (LISTEN)
vpnkit  604 thom   23u  IPv6 0x959c8f50d33a260b      0t0  TCP localhost:igrid (LISTEN)
```

### Actual Behavior

I am getting this error when running the above command:

```
$ npm run dev:start

> where2stay@1.0.0 dev:start /Users/thom/github/WhereToStayWWW
> webpack-dev-server --hot --config etc/webpack/webpack.config.js --env development --progress --bail

 10% building modules 2/2 modules 0 activeevents.js:137                            
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:19000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at doListen (net.js:1522:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! where2stay@1.0.0 dev:start: `webpack-dev-server --hot --config etc/webpack/webpack.config.js --env development --progress --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the where2stay@1.0.0 dev:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thom/.npm/_logs/2018-01-27T01_26_34_200Z-debug.log

```
### For Features; What is the motivation and/or use-case for the feature?

I completely understand that this could just be my ignorance in not understanding how this all works. If you need to just point me in the direction to find my solution, please just let me know.

Thom

**Comment by SpaceK33z** [comment]
Sorry, I have no idea. Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).
