### ISSUE TITLE
progress flag is broken - log() is not a function

### ISSUE THREAD

**Issue by gartz** [webpack/webpack-dev-server#1303]
* Operating System: Linux
* Node Version: v8.9.4
* NPM Version: 5.6.0
* webpack Version: 4.0.0-beta.0
* webpack-dev-server Version: 3.0.0-alpha6

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```
/code/node_modules/webpack-dev-server/lib/cli/util.js:51
      log();
      ^

TypeError: log is not a function
    at ready (/code/node_modules/webpack-dev-server/lib/cli/util.js:51:7)
    at Server.devServer.listen (/code/node_modules/webpack-dev-server/lib/cli/start.js:61:7)
    at Server.returnValue.server.listen (/code/node_modules/webpack-dev-server/lib/DevServer.js:179:18)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Expected Behavior
To not fail when using `--progress` and show the progress.

### Actual Behavior
It crashes because it calls an undefined function.

### For Bugs; How can we reproduce the behavior?
Use the `--progress` flag in the cli

### For Features; What is the motivation and/or use-case for the feature?
Cool progress in the console :)

**Comment by SpaceK33z** [comment]
Fixed in latest beta.
