### ISSUE TITLE
webpack-dev-server crashes on webpack compilation

### ISSUE THREAD

**Issue by hugmanrique** [webpack/webpack-dev-server#1309]
* Operating System: Windows 10
* Node Version: 8.1.4
* NPM Version: 5.5.1
* webpack Version: 4.0.0-beta.1
* webpack-dev-server Version: 3.0.0-alpha6

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require('path');

const production = process.env.NODE_ENV === 'production';
const appPath = path.resolve(__dirname, 'src');
const distPath = path.resolve(__dirname, 'dist');

module.exports = {
  entry: appPath,
  mode: 'development',
  output: {
    filename: '[name].js',
    path: distPath
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      }
    ]
  }
};
```

Running with `webpack-dev-server`

### Expected Behavior
webpack-dev-server reloads the page with the new changes.

### Actual Behavior
webpack-dev-server *sometimes* crashes with the following error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
```

### For Bugs; How can we reproduce the behavior?
Create a webpack config (on development mode), run `webpack-dev-server`, make some changes, save and wait for webpack to bundle your assets.

**Comment by michael-ciniawsky** [comment]
Please try `webpack-dev-server@3.0.0-beta.1` which reverted some of the changes made in `webpack-dev-server@3.0.0-alpha*`, this should not happen anymore now

**Comment by Apidcloud** [comment]
Using `webpack-dev-server@3.0.0-beta.1` also **solved the following issue**:
```bash
node_modules\webpack-dev-server\lib\cli\util.js:51
      log();
      ^

TypeError: log is not a function
    at ready (D:\Workspace\Github\scarlett-blast\node_modules\webpack-dev-server\lib\cli\util.js:51:7)
    at Server.devServer.listen (D:\Workspace\Github\scarlett-blast\node_modules\webpack-dev-server\lib\cli\start.js:61:7)
    at Server.returnValue.server.listen (D:\Workspace\Github\scarlett-blast\node_modules\webpack-dev-server\lib\DevServer.js:179:18)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1371:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
