### ISSUE TITLE
Cannot find module '*/node_modules/webpack-dev-server/cli.js'

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack-dev-server#1320]
* Operating System: macOS 10.13.3
* Node Version: 8.9.3
* NPM Version: 5.6.0
* webpack Version: 4.0.0
* webpack-dev-server Version: webpack-dev-server 3.0.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Please check my github [repo](https://github.com/chenxsan/webpack-dev-server-demo)

### For Bugs; How can we reproduce the behavior?

1. Clone https://github.com/chenxsan/webpack-dev-server-demo
2. Run `npx webpack serve`

```
npx webpack serve

✖ We didn't find any webpack-dev-server dependency in your project,
  'webpack serve' requires you to have it installed 

? Do you want to install it? (default: Y) Yes
? What kind of dependency do you want it to be under? (default: devDependency) devDependency
npm WARN rm not removing /Users/sam/tmp/webpack-dev-server-demo/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/sam/tmp/webpack-dev-server-demo/node_modules/fsevents/node_modules/node-pre-gyp

> fsevents@1.1.3 install /Users/sam/tmp/webpack-dev-server-demo/node_modules/fsevents
> node install

[fsevents] Success: "/Users/sam/tmp/webpack-dev-server-demo/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN webpack-dev-server@3.0.0 requires a peer of webpack@^4.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server-demo@1.0.0 No description
npm WARN webpack-dev-server-demo@1.0.0 No repository field.

+ webpack-dev-server@3.0.0
added 240 packages, removed 531 packages and updated 341 packages in 10.196s
✖ Serve aborted due to some errors
{ Error: Cannot find module '/Users/sam/tmp/webpack-dev-server-demo/node_modules/webpack-dev-server/cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (/Users/sam/tmp/webpack-dev-server-demo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at serve (/Users/sam/tmp/webpack-dev-server-demo/node_modules/webpack-cli/lib/commands/serve.js:89:10)
    at processPromise.then._ (/Users/sam/tmp/webpack-dev-server-demo/node_modules/webpack-cli/lib/commands/serve.js:150:16)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

**Comment by SpaceK33z** [comment]
Thanks for filing this bug report. Do note that this is a bug in webpack-cli. I honestly didn't even know that this was a feature 😅.

**Comment by chenxsan** [comment]
So the `cli.js` doesn't exist in `webpack-dev-server`?

**Comment by SpaceK33z** [comment]
No, it has existed only in the `next` branch for a while as part of a huge refactor, but that refactor wasn't finished.
