### ISSUE TITLE
npm 5.7.1. incompatibility issue

### ISSUE THREAD

**Issue by AKFourSeven** [webpack/webpack-dev-server#1332]
* Operating System: macOs Sierra
* Node Version: 9.6.1.
* NPM Version: 5.7.1.
* webpack Version: 3.9.1
* webpack-dev-server Version: 2.9.5

- [x] This is a **bug**
- [ ] This is a **modification** request

I just upgraded to npm latest (version 5.7.1.) and it seems to be quite displeased by my version of webpack or webpack-dev-server.
### Code

the console output
```bash
  // additional code, remove if not needed.
> selfcare@1.0.0 start /Users/user/PROJECTS/myproject
> webpack-dev-server --open

events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3030
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1353:14)
    at listenInCluster (net.js:1394:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1509:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! selfcare@1.0.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the selfcare@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-03-03T00_38_24_700Z-debug.log
```

the error log
```bash
7 verbose lifecycle selfcare@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle selfcare@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/PROJECTS/myproject/node_modules/.bin:/Users/user/.nvm/versions/node/v9.6.1/bin:/Users/user/PROJECTS/myotherproject/scripts:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:
9 verbose lifecycle selfcare@1.0.0~start: CWD: /Users/user/PROJECTS/myproject
10 silly lifecycle selfcare@1.0.0~start: Args: [ '-c', 'webpack-dev-server --open' ]
11 silly lifecycle selfcare@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle selfcare@1.0.0~start: Failed to exec start script
13 verbose stack Error: selfcare@1.0.0 start: `webpack-dev-server --open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:127:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:127:13)
13 verbose stack     at maybeClose (internal/child_process.js:933:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid selfcare@1.0.0
15 verbose cwd /Users/user/PROJECTS/myproject
16 verbose Darwin 17.4.0
17 verbose argv "/Users/user/.nvm/versions/node/v9.6.1/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.6.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error selfcare@1.0.0 start: `webpack-dev-server --open`
22 error Exit status 1
23 error Failed at the selfcare@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
### Expected Behavior
I was expecting the command to run properly as it did minutes before I install npm latest version. It seems to be incompatible with my webpack or webpack-dev-server version
### Actual Behavior
It failed as you can see above.

### For Bugs; How can we reproduce the behavior?
Probably upgrading to npm 5.7.1. and getting the same webpack-dev-server version as me

**Comment by SpaceK33z** [comment]
The error says the port 3030 is already in use. Please make sure nothing runs anymore on that port. In some cases there can be a zombie process running on that port. You can use the command `lsof` to find what program runs on a port.
