### ISSUE TITLE
Cannot create bundle.js with Webpack -p command

### ISSUE THREAD

**Issue by chikarao** [webpack/webpack-dev-server#1342]
I am preparing my project to be hosted on Heroku and am going through some basic steps such as editing my scripts on my package.json. There, I am tripping over creating a bundle.js on Webpack, when as a check, I'm running $webpack -p. The command does not create the bundle.js file my project directory as expected.

Below is my package.json (I have done sudo NPM install -g webpack webpack-cli -D on my Mac terminal).

Further, I cannot $NPM start my project in the localhost:8080. I get 'Server started' from my server.js file in my terminal but the project does not render on my local host.

When I push to Heroku, the logs show webpack -p ran and the build says successful, but the webpage shows nothing.

What am I doing wrong? Thanks in advance.

Here is my error in the terminal when I now run $webpack -p:

* Operating System: Mac
* Node Version: v9.3.0
* NPM Version: 4.6.1
* webpack Version: "^1.12.9",
* webpack-dev-server Version: "^1.14.0"
* webpack-cli Version: "^2.0.11"

### Code
Here is the error:

➜  weatherApp git:(master) ✗ webpack -p                                [system]
/Users/oc/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/webpack.js:237
                throw err;
                ^

TypeError: validateSchema is not a function
    at processConfiguredOptions (/Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/convert-argv.js:156:48)
    at module.exports (/Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/convert-argv.js:150:10)
    at yargs.parse (/Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/webpack.js:234:39)
    at Object.parse (/Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/webpack.js:212:8
    at Object.<anonymous> (/Users/okadachikara/react-courses/projects/weatherApp/node_modules/webpack-cli/bin/webpack.js:502:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/webpack-cli/bin/webpack.js:15:3
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:502:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)

Here is my package.json:

{
  "name": "redux-simple-starter",
  "version": "1.0.0",
  "description": "Simple starter package for Redux with React and Babel support",
  "main": "index.js",
  "repository": "git@github.com:StephenGrider/ReduxSimpleStarter.git",
  "scripts": {
    "start": "node server.js",
    "dev": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "postinstall": "webpack -p",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^0.14.7",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "babel-preset-stage-1": "^6.1.18",
    "express": "^4.16.2",
    "lodash": "^3.10.1",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-redux": "4.3.0",
    "react-router": "^2.0.1",
    "react-sparklines": "^1.6.0",
    "redux": "^3.0.4",
    "redux-promise": "^0.5.3"
  }
}

Here is my server.js:

const express = require('express');
const path = require('path');

const port = process.env.PORT || 8080;
const app = express();

app.use(express.static(__dirname));

app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'index.html'));
});

app.listen(port);
console.log('Server started');

Here is my webpack config file:

module.exports = {
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname,
    publicPath: '/',
    filename: 'bundle.js'
  },
  module: {
    loaders: [{
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        presets: ['react', 'es2015', 'stage-1']
      }
    }]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devServer: {
    historyApiFallback: true,
    contentBase: './'
  }
};

**Comment by hamms011** [comment]
I have the same problem, can anyone tell me the solution?
