### ISSUE TITLE
throw new Error('invalid "instanceof" keyword value ' + c);

### ISSUE THREAD

**Issue by john1jan** [webpack/webpack-dev-server#1355]
Getting this error while running 
```webpack-dev-server --config ./webpack.client.js --hot```
* Operating System: Mac OS High Sierra
* Node Version: 9.9.0
* NPM Version: 5.7.1
* webpack Version: 4.1.1
* webpack-dev-server Version:3.1.1
Full stacktrace

```
node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:52
    throw new Error('invalid "instanceof" keyword value ' + c);
    ^

Error: invalid "instanceof" keyword value Promise
    at getConstructor (node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:52:11)
    at Ajv.compile (node_modules/webpack/node_modules/ajv-keywords/keywords/instanceof.js:21:27)
    at Object.useCustomRule (node_modules/webpack/node_modules/ajv/lib/compile/index.js:275:26)
    at Object.generate_custom [as code] (node_modules/webpack/node_modules/ajv/lib/dotjs/custom.js:32:24)
    at Object.generate_validate [as validate] (node_modules/webpack/node_modules/ajv/lib/dotjs/validate.js:347:35)
    at Object.generate_anyOf [as code] (node_modules/webpack/node_modules/ajv/lib/dotjs/anyOf.js:34:27)
    at generate_validate (node_modules/webpack/node_modules/ajv/lib/dotjs/validate.js:347:35)
    at localCompile (node_modules/webpack/node_modules/ajv/lib/compile/index.js:87:22)
    at Ajv.compile (node_modules/webpack/node_modules/ajv/lib/compile/index.js:56:13)
    at Ajv._compile (node_modules/webpack/node_modules/ajv/lib/ajv.js:358:27)
    at Ajv.compile (node_modules/webpack/node_modules/ajv/lib/ajv.js:118:37)
    at validateObject (node_modules/webpack/lib/validateSchema.js:36:23)
    at validateSchema (node_modules/webpack/lib/validateSchema.js:31:10)
    at processConfiguredOptions (node_modules/webpack-cli/bin/convert-argv.js:156:48)
    at module.exports (node_modules/webpack-cli/bin/convert-argv.js:150:10)
    at Object.<anonymous> (node_modules/webpack-dev-server/bin/webpack-dev-server.js:234:54)
```

**Comment by silky** [comment]
why do bad things happen to good people?

we manually hacked our package.json to use webpack 4.2.0 and this error goes away!

woo!

**Comment by DCbryant** [comment]
I solved by lowerring my webpack-dev-server version,The problem is there

**Comment by ndabAP** [comment]
@DCbryant which version do you use now?

**Comment by DCbryant** [comment]
@ndabAP 2.9.1

**Comment by styks1987** [comment]
I had a similar issue but it was due to not having webpack-cli installed.

**Comment by rohan-paul** [comment]
Had this issue today, and went away, after upgrading webpack to 4.5.0 and also installing webpack-cli locally..

**Comment by zvs001** [comment]
`npm i webpack@latest -g` helps me

**Comment by MgSam** [comment]
So this happened because webpack pushed breaking changes in a minor version and most people probably have their `package.json` file with a carrot or tilde in front of the webpack dependencies. Removing that carrot or tilde to freeze to the version specified and running `npm install` fixed the problem for me.

I think it's extremely irresponsible for webpack to have made these breaking changes in a minor version. The webpack CLI separation should have only occurred in a major release. You have literally millions of people depending on this package, please put some more thought into release numbers.

**Comment by GQM-dong** [comment]
maybe you can change your package.json
update the webpack to 4.X 
delete your node_modules
npm install again
and then it's work

**Comment by BrandonDickson** [comment]
@kopax, I was able to solve this by updating lerna to `2.10.0` from `2.0.0-rc5`.  I believe the problem stemmed from the fact that I was updating webpack one project at a time, and I was hoisting the modules with lerna, but the update resolved it.

**Comment by SpaceK33z** [comment]
It looks like this issue is related to webpack and/or webpack-cli, not webpack-dev-server, so I'm closing this. If you believe this is an issue in WDS please provide a test repository, because I cannot reproduce this.

**Comment by kunwang0916** [comment]
`npm install webpack-dev-server@2.x`, works for me.

**Comment by realgs** [comment]
I read this topic for a second time within 2 weeks so I decided to write down my own suggestions in case I will come back anytime in the future;) The below is a complete list of dependencies I had to upgrade to upgrade from vulnerable react-dom@16.0.0 to @16.0.1:
 
❯ yarn add react@16.0.1 react-dom@16.0.1 webpack-dev-server@3.1.14 live-server@1.2.1 extract-text-webpack-plugin@next
❯ yarn add -D webpack-cli

remove node_modules
npm install
add --mode development to your CLI command (webpack-dev-server --mode development)
try again to start the project with yarn run dev-server (or whatever is your script to run the project locally)

**Comment by AbuAmeeer** [comment]
you can use npm run build instead of

**Comment by imzubair10** [comment]
following worked for me
npm install webpack-dev-server@2.11.0 --save-dev

**Comment by rramiachraf** [comment]
> 
> 
> following worked for me
> npm install webpack-dev-server@2.11.0 --save-dev

Thank you, this is actually worked..
