### ISSUE TITLE
AssertionError in spdy-transport consistently causing failures while running in Chrome 69

### ISSUE THREAD

**Issue by bdpartridge** [webpack/webpack-dev-server#1491]
* Operating System: macOS High Sierra (10.13.6)
* Node Version: 8.11.1
* Yarn Version: 1.6.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.6

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I'm not including our webpack config for now, but I can include a stripped-down version if it's really needed to reproduce the problem.

### Expected Behavior

*webpack-dev-server* works like it did in Chrome <69, and like it continues to work in other browsers (like Firefox).

### Actual Behavior

After several incremental recompiles, the process errors out due to an AssertionError in the spdy-transport library:

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/priority.js:72:3)
    at PriorityNode.remove (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/priority.js:61:15)
    at PriorityTree.add (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/priority.js:157:23)
    at Stream._initPriority (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/stream.js:101:25)
    at new Stream (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/stream.js:75:8)
    at Connection._createStream (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/connection.js:391:16)
    at Connection._handleHeaders (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/connection.js:438:21)
    at Connection._handleFrame (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/connection.js:321:10)
    at Parser.<anonymous> (/Users/bpartridge/forward/fwd/gui/node_modules/spdy-transport/lib/spdy-transport/connection.js:158:10)
    at emitOne (events.js:116:13)
```

This only seems to happen in Chrome, and only started after upgrading to 69.0.3497.81 (Official Build) (64-bit).

### For Bugs; How can we reproduce the behavior?

* Run *webpack-dev-server*.
* Open URL for server in Chrome 69.
* Trigger several incremental rebuilds. For me, it routinely took around 5-7 rebuilds before the error was triggered.
* Observe that process fails due to AssertionError noted above.

Might be related to spdy-http2/spdy-transport#47.

**Comment by evilebottnawi** [comment]
@bdpartridge yep, please create minimum reproducible test repo, thanks!

**Comment by davidjoy** [comment]
For those blocked by this, @misterfresh's quick, hacky fix described in this comment over on https://github.com/spdy-http2/spdy-transport/issues/47 seems to have temporarily solved it for us:

https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-369020176

Not something I want to leave in the code base, but it at least lets us keep using our dev servers for the moment.

**Comment by pladaria** [comment]
@davidjoy, adding `spdy: {protocols: ['http/1.1']}spdy: {protocols: ['http/1.1']}` to https options in dev-server config workarounded this issue for us

**Comment by rathpc** [comment]
I also experienced this issue with the following config:

Operating System: macOS Sierra (10.12.6)
Node Version: 8.11.2
NPM Version: 6.1.0
webpack Version: 2.7.0
webpack-dev-server Version: 2.11.2

I am using the patch fix mentioned by @misterfresh with some additional logic until an official fix is released.

**Comment by evilebottnawi** [comment]
Feel free to PR :+1:

**Comment by Ailuue** [comment]
> > @davidjoy, simply adding `spdy: {protocols: ['http/1.1']}` to https options in dev-server config workarounded this issue for us
> 
> Thank you. That helps me.
> 
> ```
> devServer: {
>     host: '0.0.0.0',
>     port: 3000,
>     https: {
>         spdy: {
>             protocols: ['http/1.1']
>         }
>     }
> }
> ```

Any way to do this from a create-react-app state?

**Comment by evilebottnawi** [comment]
Maybe we can use this as default property for `protocols`

**Comment by evilebottnawi** [comment]
@odinho fixed in https://github.com/webpack/webpack-dev-server/issues/1491, will be shipped in near future

**Comment by Imran-Siddiquii** [comment]
VM51:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1)
4043 @ VM51:2
r @ VM51:2
8048 @ VM51:2
r @ VM51:2
8641 @ VM51:2
r @ VM51:2
(anonymous) @ VM51:2
(anonymous) @ VM51:2
(anonymous) @ VM51:2
e.onload @ index.js:1
load (async)
be @ index.js:1
he @ index.js:1
tryDismissErrorOverlay @ webpackHotDevClient.js:184
onSuccessfulHotUpdate @ webpackHotDevClient.js:150
handleApplyUpdates @ webpackHotDevClient.js:257
(anonymous) @ webpackHotDevClient.js:273
Promise.then (async)
tryApplyUpdates @ webpackHotDevClient.js:271
handleWarnings @ webpackHotDevClient.js:147
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:76 The development server has disconnected.
Refresh the page if necessary.

why this is happening
