### ISSUE TITLE
typescript configuration files seem not to be accepted

### ISSUE THREAD

**Issue by simpert** [webpack/webpack-dev-server#1515]
* Operating System: win
* Node Version: 8.4.11
* NPM Version: what 8.4.11 installs
* webpack Version: new
* webpack-dev-server Version: new

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```typescript
  // additional code, remove if not needed.
import * as webpack from 'webpack';
import * as merge from 'webpack-merge';
import * as path from 'path';
import baseConfig from './webpack.renderer.config';

const spawn = require( 'child_process' ).spawn;

module.exports = merge.smart(
    baseConfig,
    {
        entry:
        {
            app: [ 'react-hot-loader/patch', './source/app.dev.tsx' ]
        },
        mode: 'development',
        module:
        {
            rules: [
                {
                    test: /\.tsx?$/,
                    include: [ path.resolve( __dirname, 'source' ) ],
                    exclude: [ path.resolve( __dirname, 'source', 'main.ts' ) ],
                    loaders: [
                        'react-hot-loader/webpack',
                        'ts-loader'
                    ]
                } ]
        },
        plugins: [
            new webpack.NamedModulesPlugin(),
            new webpack.HotModuleReplacementPlugin()
        ],
        devServer:
        {
            port: 9223,
            contentBase: './',
            //index: 'index.html',
            hot: true,
            headers: { 'Access-Control-Allow-Origin': '*' },
            historyApiFallback:
            {
                //verbose: true,
                disableDotRule: false
            },
            before ()
            {
                if ( process.env.START_HOT )
                {
                    console.log( 'Starting main process' );
                    spawn( 'npm', [ 'run', 'start:main' ],
                        {
                            shell: true,
                            env: process.env,
                            stdio: 'inherit'
                        } )
                        .on( 'close', code => process.exit( code ) )
                        .on( 'error', spawnError => console.error( spawnError ) );
                }
            }
        }
    }
);
```

### Expected Behavior
should be able to pass a `.ts` file like `webpack-dev-server --config webpack.renderer.hot.dev.config.ts` as `webpack` fully supports this.
### Actual Behavior
syntax errors
```
(function (exports, require, module, __filename, __dirname) { import * as webpack from 'webpack';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at WEBPACK_OPTIONS (C:\Users\tommy\AppData\Roaming\nvm\v8.11.4\node_modules\webpack-cli\bin\convert-argv.js:133:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sidelinesnap@1.0.1 start:renderer:hot: `webpack-dev-server --config webpack.renderer.hot.dev.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sidelinesnap@1.0.1 start:renderer:hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tommy\AppData\Roaming\npm-cache\_logs\2018-09-30T22_40_38_756Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sidelinesnap@1.0.1 start:hot: `cross-env START_HOT=1 npm run start:renderer:hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sidelinesnap@1.0.1 start:hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
### For Bugs; How can we reproduce the behavior?
run `webpack-dev-server --config webpack.renderer.hot.dev.config.ts` with contents above

**Comment by stepquick** [comment]
I actually just came across this recently trying to set up an environment for something similar. Were you able to get it working?

I made a gist of the webpack config i started with and seemed to work for me: https://gist.github.com/stepquick/ffd78fa456ab91a2ccbb787e1e7236ed

I followed the guidelines for webpack and ts: https://webpack.js.org/guides/typescript/

From what I noticed I got import errors when I didn't have ts-node installed. Installing it did the trick for me.

**Comment by ematipico** [comment]
The guide talks about how to use typescript on your source code, not on your configuration.

If you want to run typescript on you configuration, use `ts-node`, if you don't please revert to see simple JavaScript. This is not an issue related to this project.

**Comment by stepquick** [comment]
I didn't mean to imply I was talking about my source code, I meant the config file. Following the guide for typescript is what I was missing to use my config.ts file properly. Installing ts-node resolved it for me.

**Comment by simpert** [comment]
I figured it out. The problem I had was mistake in code `module.exports = `.  I think the error I received kinda through me off that for a bit as according to errors I was looking for issue with the imports.

changing to `const config = merge...` and following `export default config;` did the trick.
