### ISSUE TITLE
use api start,get error Cannot set property 'log' of undefined.

### ISSUE THREAD

**Issue by rc452860** [webpack/webpack-dev-server#1565]
* Operating System: Win10
* Node Version: v8.11.3
* NPM Version: v8.11.3
* webpack Version: ^4.24.0
* webpack-dev-server Version: ^3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const webpack = require('webpack');
// const apiMocker = require('webpack-api-mocker');


module.exports = {
  mode: 'development',
  entry: ['babel-polyfill', path.join(__dirname, 'src', 'app', 'index')],
  resolve: {
    extensions: ['.json', '.js', '.jsx', '.css', '.tsx', '.ts']
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'build', 'app'),
    chunkFilename: '[name].[chunkhash:5].chunk.js',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        loader: 'awesome-typescript-loader',
        options: {
          configFileName: "src/app/tsconfig.json",
        }
      },
      {
        enforce: "pre",
        test: /\.js$/,
        loader: "source-map-loader"
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: ['babel-preset-react', 'babel-preset-env']
        }
      }, {
        test: /\.(jpg|png|gif|svg|eot|ttf|woff|woff2)$/,
        loader: 'url-loader',
        options: {
          limit: 4192
        }
      }, {
        test: /\.(css)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'style-loader'
          }, {
            loader: 'css-loader',
            options: {
              modules: true       //开启css modules
            }
          }
        ]
      }, {
        test: /\.(sass|scss)$/,
        exclude: /node_modules/,
        use: [{
          loader: "style-loader" // 将 JS 字符串生成为 style 节点
        }, {
          loader: "css-loader" // 将 CSS 转化成 CommonJS 模块
        }, {
          loader: "sass-loader" // 将 Sass 编译成 CSS
        }]
      }
    ]
  },
  watch: false,
  profile: true,
  cache: true,
  // devServer: {
  //   contentBase: path.join(__dirname, 'dist','renderer'),
  //   compress: true,
  //   hot: true,
  //   port: 9000,
  //   before(app){
  //     apiMocker(app,path.resolve(__dirname,'.mock'));
  //   }
  // },
  plugins: [
    new CleanWebpackPlugin([path.resolve(__dirname, 'build', 'app')]),
    new HtmlWebpackPlugin({
      title: 'sakura',
      template: './src/app/index.html'
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
  ],
  devtool: 'eval-source-map',
  // devServer:{
  //   contentBase: path.join(__dirname, 'build/react'),
  //   compress: true,
  //   port: 9000
  // }
};
```

```js
  // additional code, remove if not needed.
var port = 8080;
  var compiler = webpack(Object.assign({}, webpack_config, {
    devServer: {
      stats: {
        color: true
      }
    }
  }));
  var server = WebpackDevServer(compiler, {});
  server.listen(port, '127.0.0.1', () => {
    console.log(`Starting server on http://localhost:${port}`);
  })
```

### Actual Behavior
```
[00:46:39] TypeError: Cannot set property 'log' of undefined
    at Server (D:\work\outline-client\node_modules\webpack-dev-server\lib\Server.js:65:12)
    at Gulp.<anonymous> (D:\work\outline-client\gulpfile.js:306:16)
    at module.exports (D:\work\outline-client\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\work\outline-client\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\work\outline-client\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\work\outline-client\node_modules\orchestrator\index.js:134:8)
    at D:\work\outline-client\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
error Command failed with exit code 1.
```

**Comment by evilebottnawi** [comment]
Strange, looks like a bug, feel free to send a PR

**Comment by rc452860** [comment]
@evilebottnawi the server.js has three arguments. the last arguments are log. but in examples last argument lost.

**Comment by evilebottnawi** [comment]
I think we should setup default value

**Comment by rc452860** [comment]
@evilebottnawi I think I was wrong. actually, I forget new.
```
- var server = WebpackDevServer(compiler, {});
+ var server = new WebpackDevServer(compiler, {});
```
