### ISSUE TITLE
webpack-dev-server failing on Node v11.3 due to SPDY module

### ISSUE THREAD

**Issue by nzapponi** [webpack/webpack-dev-server#1592]
* Operating System: macOS v10.14
* Node Version: v11.3.0
* NPM Version: 6.4.1
* webpack Version: 3.5.1
* webpack-dev-server Version: 2.8.2

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  > NODE_ENV=development webpack-dev-server --https

Generating SSL Certificate
Project is running at https://localhost:8888/webpack-dev-server/
webpack output is served from /dist
Content not from webpack is served from /Users/nzapponi/Git Repositories/Quip/meeting-scheduler/app/dist
Hash: 5f448c58750683f7e764
Version: webpack 3.5.1
Time: 5245ms
      Asset      Size  Chunks                    Chunk Names
     app.js    959 kB       0  [emitted]  [big]  main
    app.css   11.3 kB       0  [emitted]         main
 app.js.map    1.2 MB       0  [emitted]         main
app.css.map  84 bytes       0  [emitted]         main
   [1] ./node_modules/moment/moment.js 147 kB {0} [built]
  [19] ./node_modules/core-js/modules/_core.js 122 bytes {0} [built]
  [88] ./node_modules/core-js/modules/es6.array.iterator.js 1.12 kB {0} [built]
 [114] ./node_modules/core-js/modules/es6.regexp.exec.js 178 bytes {0} [built]
 [115] ./node_modules/core-js/modules/es6.regexp.flags.js 201 bytes {0} [built]
 [258] multi babel-polyfill quip-apps-compat ./src/root.jsx 52 bytes {0} [built]
 [259] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [260] (webpack)/buildin/global.js 509 bytes {0} [built]
 [261] ./node_modules/core-js/shim.js 8.22 kB {0} [built]
 [457] ./node_modules/regenerator-runtime/runtime.js 24.1 kB {0} [built]
 [458] ./node_modules/core-js/fn/regexp/escape.js 108 bytes {0} [built]
 [461] ./node_modules/quip-apps-compat/index.js 3.44 kB {0} [built]
 [462] ./src/root.jsx 1.2 kB {0} [built]
 [465] ./src/containers/App/App.js 19.4 kB {0} [built]
 [476] ./src/model.js 6.8 kB {0} [built]
    + 470 hidden modules
Child extract-text-webpack-plugin ../../../Git Repositories/Quip/meeting-scheduler/node_modules/extract-text-webpack-plugin/dist ../../../Git Repositories/Quip/meeting-scheduler/node_modules/css-loader/index.js??ref--1-2!../../../Git Repositories/Quip/meeting-scheduler/node_modules/postcss-loader/lib/index.js??ref--1-3!../../../Git Repositories/Quip/meeting-scheduler/node_modules/less-loader/lib/loader.js!../../../Git Repositories/Quip/meeting-scheduler/src/components/Scheduler/Scheduler.less:
       [0] ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]"}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/less-loader/lib/loader.js!./src/components/Scheduler/Scheduler.less 647 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin ../../../Git Repositories/Quip/meeting-scheduler/node_modules/extract-text-webpack-plugin/dist ../../../Git Repositories/Quip/meeting-scheduler/node_modules/css-loader/index.js??ref--1-2!../../../Git Repositories/Quip/meeting-scheduler/node_modules/postcss-loader/lib/index.js??ref--1-3!../../../Git Repositories/Quip/meeting-scheduler/node_modules/less-loader/lib/loader.js!../../../Git Repositories/Quip/meeting-scheduler/src/components/dialog/dialog.less:
       [0] ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]"}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/less-loader/lib/loader.js!./src/components/dialog/dialog.less 619 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin ../../../Git Repositories/Quip/meeting-scheduler/node_modules/extract-text-webpack-plugin/dist ../../../Git Repositories/Quip/meeting-scheduler/node_modules/css-loader/index.js??ref--1-2!../../../Git Repositories/Quip/meeting-scheduler/node_modules/postcss-loader/lib/index.js??ref--1-3!../../../Git Repositories/Quip/meeting-scheduler/node_modules/less-loader/lib/loader.js!../../../Git Repositories/Quip/meeting-scheduler/src/components/Tooltip/Tooltip.less:
       [0] ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]"}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/less-loader/lib/loader.js!./src/components/Tooltip/Tooltip.less 1.14 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin ../../../Git Repositories/Quip/meeting-scheduler/node_modules/extract-text-webpack-plugin/dist ../../../Git Repositories/Quip/meeting-scheduler/node_modules/css-loader/index.js??ref--1-2!../../../Git Repositories/Quip/meeting-scheduler/node_modules/postcss-loader/lib/index.js??ref--1-3!../../../Git Repositories/Quip/meeting-scheduler/node_modules/less-loader/lib/loader.js!../../../Git Repositories/Quip/meeting-scheduler/src/components/Scheduler/Day/Day.less:
       [0] ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]"}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/less-loader/lib/loader.js!./src/components/Scheduler/Day/Day.less 7.07 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin ../../../Git Repositories/Quip/meeting-scheduler/node_modules/extract-text-webpack-plugin/dist ../../../Git Repositories/Quip/meeting-scheduler/node_modules/css-loader/index.js??ref--1-2!../../../Git Repositories/Quip/meeting-scheduler/node_modules/postcss-loader/lib/index.js??ref--1-3!../../../Git Repositories/Quip/meeting-scheduler/node_modules/less-loader/lib/loader.js!../../../Git Repositories/Quip/meeting-scheduler/src/components/Scheduler/Day/Slot/Slot.less:
       [0] ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]"}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/less-loader/lib/loader.js!./src/components/Scheduler/Day/Slot/Slot.less 4.8 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
webpack: Compiled successfully.
buffer.js:72
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (buffer.js:72:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:121:17)
    at Stream.<anonymous> (/Users/nzapponi/Git Repositories/Quip/meeting-scheduler/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:187:15)
    at endReadableNT (/Users/nzapponi/Git Repositories/Quip/meeting-scheduler/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

### Expected Behavior
The server should not crash at the first request

### Actual Behavior
Webpack compiles successfully but the server crashes at the first request

### For Bugs; How can we reproduce the behavior?
Upgrade to Node v11.3 and try to run webpack-dev-server.

### For Features; What is the motivation and/or use-case for the feature?

See here: https://github.com/spdy-http2/node-spdy/issues/350

**Comment by nzapponi** [comment]
https://github.com/spdy-http2/node-spdy/issues/350

**Comment by evilebottnawi** [comment]
Thanks for issue, maybe we can find workaround

**Comment by evilebottnawi** [comment]
@nzapponi sorry for delay, problem still exists? if yes, please create minimum reproducible test repo, thanks!

**Comment by yi-ge** [comment]
The bug is fixed. https://github.com/webpack/webpack-dev-server/pull/1660

**Comment by yi-ge** [comment]
@evilebottnawi the same problem. 😄

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/1660/

**Comment by cicibobo** [comment]
Issue still exist  node - v11.11.0,   spdy - 4.0.0

**Comment by TheLarkInn** [comment]
Can you still confirm this @cicibobo?
