### ISSUE TITLE
ConcurrentCompilationError

### ISSUE THREAD

**Issue by gustavomassa** [webpack/webpack-dev-server#1602]
* Operating System: Windows 10 Pro 64bits
* Node Version: 10.14.0 (LTS)
* NPM Version: 6.4.1
* webpack Version: 4.27.1 and below
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**

### Code

```js
  // webpack.config.js
const path = require('path');
const webpack = require('webpack');
const sourcePath = path.resolve(__dirname, 'src');
const fs = require("fs");

module.exports = function makeWebpackConfig(env) {
    //set build environment
    let environment = (env) ? env : 'dev';
    if (environment !== 'dev' && environment !== 'qa' && environment !== 'prod' && environment !== 'hotfix' && environment !== 'feature' && environment !== 'release') {
        console.error(`INVALID environment => ${environment}\nValid environments: dev, qa, prod, hotfix, feature, release`);
        return null;
    }
    console.log(`Build environment => ${environment}`);

    try {
        const appConfigPath = "./src/ts/bootstrap/Config.ts";
        let appConfig = fs.readFileSync(appConfigPath, "utf8");
        appConfig = appConfig.replace(new RegExp('"', 'g'), "'");

        //hotfix, feature and release logic should increment version automatically
        if (environment === 'release' || environment === 'feature' || environment === 'hotfix') {
            const operation = environment;
            environment = 'qa';

            let currentVersion = appConfig.split('version: ')[1].split(',')[0];
            const currentVersionLine = `version: ${currentVersion},`;
            currentVersion = currentVersion.substr(1, currentVersion.length - 2).split('.');

            //version increment logic
            let major = parseInt(currentVersion[0]);
            let minor = parseInt(currentVersion[1]);
            let build = parseInt(currentVersion[2]);

            console.log(`Current Version: ${major}.${minor}.${build}`);

            switch (operation) {
                case 'release':
                    major++;
                    minor = 0;
                    build = 0;
                    break;
                case 'feature':
                    minor++;
                    build = 0;
                    break;
                case 'hotfix':
                    build++;
                    break;
            }
            //increment version
            const newVersion = `${major}.${minor}.${build}`;
            const newVersionLine = `version: ${`'${newVersion}'`},`;
            const versionIndex = appConfig.indexOf(currentVersionLine);
            appConfig = appConfig.replace(appConfig.substring(versionIndex, versionIndex + currentVersionLine.length), newVersionLine);

            console.log(`New ${operation} version: ${newVersion}`);
        }
        //set environment
        const currentEnvironment = appConfig.split('environment: ')[1].split(',')[0];
        const currentEnvironmentLine = `environment: ${currentEnvironment},`;
        const newEnvironmentLine = `environment: ${`'${environment}'`},`;
        const environmentIndex = appConfig.indexOf(currentEnvironmentLine);
        appConfig = appConfig.replace(appConfig.substring(environmentIndex, environmentIndex + currentEnvironmentLine.length), newEnvironmentLine);

        fs.writeFileSync(appConfigPath, appConfig, "utf8");

    } catch (ex) {
        console.log(ex);
        return null;
    }

    //build config object
    let config = {};
    config.context = sourcePath;

    if (!config.mode) {
        if (environment === 'dev') config.mode = 'development';
        else if (environment === 'qa') config.mode = 'production';
        else if (environment === 'prod') config.mode = 'production';
    }
    console.log('Webpack mode: ', config.mode);

    if (config.mode === 'development') config.devtool = 'inline-source-map';

    config.entry = {
        bootstrapModule: '../src/ts/bootstrap/BootstrapModule',
    };
    config.module = {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'ts-loader'
                //loader: 'awesome-typescript-loader'
            },
            {
                test: /\.css$/,
                include: [/node_modules/, sourcePath],
                loader: 'style-loader!css-loader',
            },
            {
                test: /\.scss$/,
                loader: 'style!css!sass',
            },
            {
                test: /\.html$/,
                exclude: /node_modules/,
                loader: 'html-loader',
            },
            {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'url-loader?limit=10000&mimetype=application/font-woff',
            },
            {
                test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'file-loader',
            },
            {
                test: /\.jpg$/,
                exclude: /node_modules/,
                loader: 'file'
            },
            {
                test: /\.png$/,
                exclude: /node_modules/,
                loader: 'url-loader'
            }
        ]
    };
    config.resolve = {
        extensions: ['.tsx', '.ts', '.js', '.json']
    };
    config.plugins = [
        new webpack.ProvidePlugin({
            Promise: ['es6-promise', 'Promise']
        }),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            'window.jquery': 'jquery'
        })
    ];
    config.output = {
        filename: "[name].js",
        path: sourcePath,
        //devtoolModuleFilenameTemplate: '[absolute-resource-path]'
    };
    config.optimization = {
        splitChunks: {
            cacheGroups: {
                bootstrapModule: {
                    name: "bootstrapModule",
                    test: "bootstrapModule",
                    enforce: true
                }
            }
        },
        runtimeChunk: false
    };
    return config;
}
```

```js
  // Package.json scripts
  "scripts": {
    "dev": "webpack-dev-server --env dev --mode development --progress --compress --color --lazy --content-base src/",
    "qa": "webpack --env qa --mode production --progress",
    "prod": "webpack --env prod --mode production --progress",
    "release": "webpack --env release --mode production --progress",
    "feature": "webpack --env feature --mode production --progress",
    "hotfix": "webpack --env hotfix --mode production --progress"
  },
```

### ERROR Info
```
Build environment => dev
Webpack mode:  development
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Projetos\Monaco-webpack\src
 10% building 1/1 modules 0 activei ｢wdm｣: wait until bundle 11% building 16/21 modules 5 active ...Monaco-webpack\node_modules\url\util.jsi ｢wdm｣: wait until bundle finished: /bootstrapModule.js        × ｢wdm｣: ConcurrentCompilationError: You ran Webpack twice. Each instance onlysupports a single concurrent compilation at a time.
    at Compiler.run (C:\Projetos\Monaco-webpack\node_modules\webpack\lib\Compiler.js:205:37)
    at rebuild (C:\Projetos\Monaco-webpack\node_modules\webpack-dev-middleware\lib\context.js:81:24)
    at done (C:\Projetos\Monaco-webpack\node_modules\webpack-dev-middleware\lib\context.js:59:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projetos\Monaco-webpack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:36:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projetos\Monaco-webpack\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at emitRecords.err (C:\Projetos\Monaco-webpack\node_modules\webpack\lib\Compiler.js:257:22)
    at Compiler.emitRecords (C:\Projetos\Monaco-webpack\node_modules\webpack\lib\Compiler.js:371:39)
    at emitAssets.err (C:\Projetos\Monaco-webpack\node_modules\webpack\lib\Compiler.js:251:10)    at hooks.afterEmit.callAsync.err (C:\Projetos\Monaco-webpack\node_modules\webpack\lib\Compiler.js:357:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projetos\Monaco-webpack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:10:1)
```

### For Bugs; How can we reproduce the behavior?
It's lottery, async synchronization issue, sometimes it works fine, sometimes it doesn't. Just exec "npm run dev" and launch http://localhost:8080, while the module is loading for the first time, the bug can happen.

**Comment by evilebottnawi** [comment]
Looks problem in `webpack`, please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@gustavomassa friendly ping

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Feel free to feedback.
