### ISSUE TITLE
devServer.https.cert results in error if symlink used

### ISSUE THREAD

**Issue by chaos-git** [webpack/webpack-dev-server#1805]
Discovered an issue when setting the devServer.https.cert value to the path of a symlink. Even though the destination of the symlink is a valid certificate, webpack will instead treat the filepath itself as the certificate which naturally fails.

I plan to submit a PR with a fix in the next few days by adding `fs.realpath(...)` before doing lstat on the file.

https://github.com/webpack/webpack-dev-server/blob/cf4d0d07b8ffba9d28cd627b48f74e5f4f307fc6/lib/Server.js#L606

```
/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:168
    throw err;
    ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at Server (_tls_wrap.js:819:25)
    at Server (https.js:60:14)
    at Server._init (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:62:10)
    at new Server (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:25:10)
    at Function.create (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:30:12)
    at Object.create [as createServer] (/home/myuser/workspace/myproject/node_modules/spdy/lib/spdy/server.js:286:27)
    at new Server (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/lib/Server.js:655:45)
    at startDevServer (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:160:14)
    at processOptions (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:113:5)
    at Object.<anonymous> (/home/myuser/workspace/myproject/node_modules/webpack-dev-server/bin/webpack-dev-server.js:229:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myproject@0.0.1 start: `ant generate-proctor-js && WEBPACK_PROXY=1 webpack-dev-server --config webpack.config.js --progress --colors --inline --https --cert /etc/ssl/certs/My-Dev-Cert.pem --key /etc/ssl/private/My-Dev-Cert.key`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myproject@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

**Comment by evilebottnawi** [comment]
Please use issue template in future otherwise issue was closed, thanks
