### ISSUE TITLE
TypeError: Cannot read property 'bonjour' of undefined

### ISSUE THREAD

**Issue by TheAifam5** [webpack/webpack-dev-server#1945]
- Operating System: ArchLinux
- Node Version: v11.15.0
- NPM Version: None (Yarn 1.16.0)
- webpack Version: 4.32.2
- webpack-dev-server Version: 3.5.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Should work.

### Actual Behavior
Crashes because `createConfig` get's somehow `undefined` as `argv`.

### For Bugs; How can we reproduce the behavior?
Make simple `electron-webpack` application. Works on previous versions of `webpack-dev-server` - 3.4.1.

### Logs
```
TypeError: Cannot read property 'bonjour' of undefined
      at createConfig (/home/theaifam5/Documents/Projects/TheAifam5/vscode-launcher/node_modules/webpack-dev-server/lib/utils/createConfig.js:13:12)
      at processOptions (/home/theaifam5/Documents/Projects/TheAifam5/vscode-launcher/node_modules/webpack-dev-server/lib/utils/processOptions.js:22:19)
      at processImmediate (internal/timers.js:443:21)
  From previous event:
      at processOptions (/home/theaifam5/Documents/Projects/TheAifam5/vscode-launcher/node_modules/webpack-dev-server/lib/utils/processOptions.js:9:12)
      at Object.<anonymous> (/home/theaifam5/Documents/Projects/TheAifam5/vscode-launcher/node_modules/webpack-dev-server/bin/webpack-dev-server.js:172:1)
      at Module._compile (internal/modules/cjs/loader.js:816:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
      at Module.load (internal/modules/cjs/loader.js:685:32)
      at Function.Module._load (internal/modules/cjs/loader.js:620:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
      at internal/main/run_main_module.js:21:11
```

**Comment by hiroppy** [comment]
@TheAifam5 Thanks. Could you submit the reproducible repo?

**Comment by jspears** [comment]
There is a fix in [1946](https://github.com/webpack/webpack-dev-server/issues/1946)

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/1947
