### ISSUE TITLE
TypeError: Cannot read property 'headers' of null

### ISSUE THREAD

**Issue by d1y** [webpack/webpack-dev-server#2243]
```console
C:\Users\Administrator\Desktop\work\xxxx\xcode\node_modules\webpack-dev-server\lib\servers\SockJSServer.js:67
      f(connection, connection.headers);
                               ^

TypeError: Cannot read property 'headers' of null
    at Server.socket.on (C:\Users\Administrator\Desktop\work\xxxx\xcode\node_modules\webpack-dev-server\lib\servers\SockJSServer.js:67:32)
    at Server.emit (events.js:198:13)
    at App.emit (C:\Users\Administrator\Desktop\work\xxxx\xcode\node_modules\sockjs\lib\sockjs.js:196:29)
    at C:\Users\Administrator\Desktop\work\xxxx\xcode\node_modules\sockjs\lib\transport.js:111:25
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WV@0.1.0 dev:h5: `cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WV@0.1.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-09-09T05_53_18_722Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Administrator\Desktop\work\xxxx\xcode>
C:\Users\Administrator\Desktop\work\xxxx\xcode>
C:\Users\Administrator\Desktop\work\xxxx\xcode>yarn serve
yarn run v1.17.3
```

**Comment by evilebottnawi** [comment]
Fixed in master, release will be in near future

**Comment by developdeez** [comment]
Any work around in mean time. I only notice this when testing on mobile
