### ISSUE TITLE
Yarn PnP support

### ISSUE THREAD

**Issue by dutzi** [webpack/webpack-dev-server#2256]
When trying to use Yarn PnP on my project I get the following error when trying to run `yarn run dev` (`webpack-dev-server --host 0.0.0.0 --port 9004 --mode development`):

```
Error: Couldn't find a suitable Node resolution for unqualified path "/Users/eldad/.config/yarn/global/node_modules/lib/Server"
```

I'm running Yarn v1.17.3 and webpack-dev-server 3.8.1

- Operating System: OSX 10.14.6 (18G87)
- Node Version: v10.15.1
- NPM Version: 6.4.1
- Yarn Version: 1.17.3
- webpack Version: 4.40.2
- webpack-dev-server Version: 3.8.1
- Browser: Chrome 77

- [x] This is a **modification** request

**Update**

I think this happens when webpack-dev-server is installed globally, when installed locally I get the following error:

```
Error: Package "webpack-dev-server@pnp:3a98cc36950646e4b83e17ac76dfd8c7ae624d5c" (via "/Users/eldad/work/conversation/.pnp/externals/pnp-3a98cc36950646e4b83e17ac76dfd8c7ae624d5c/node_modules/webpack-dev-server/bin/webpack-dev-server.js") is trying to require the package "webpack-cli" (via "webpack-cli/bin/config-yargs") without it being listed in its dependencies (webpack, ansi-html, bonjour, chokidar, compression, connect-history-api-fallback, debug, del, express, html-entities, http-proxy-middleware, import-local, internal-ip, ip, is-absolute-url, killable, loglevel, opn, p-retry, portfinder, schema-utils, selfsigned, semver, serve-index, sockjs, sockjs-client, spdy, strip-ansi, supports-color, url, webpack-dev-middleware, webpack-log, ws, yargs, webpack-dev-server)
    at makeError (/Users/eldad/work/conversation/.pnp.js:55:17)
    at Object.resolveToUnqualified (/Users/eldad/work/conversation/.pnp.js:28604:17)
    at Object.resolveRequest (/Users/eldad/work/conversation/.pnp.js:28675:31)
    at Function.Module._resolveFilename (/Users/eldad/work/conversation/.pnp.js:28857:30)
    at Function.Module._load (/Users/eldad/work/conversation/.pnp.js:28773:31)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/eldad/work/conversation/.pnp/externals/pnp-3a98cc36950646e4b83e17ac76dfd8c7ae624d5c/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by vhiairrassary** [comment]
`webpack-cli` is required at https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L65 but it is listed as a `devDependencies` and not as a `dependencies`, which is not compatible with Yarn PnP.

I created a simple PR https://github.com/webpack/webpack-dev-server/pull/2257, but I don't know the webpack-dev-server's internals to be sure about the change.

**Comment by dutzi** [comment]
Ok, I stopped using the webpack-cli from the terminal and tried using it as a node module and it seems to work. Still getting a ton of error regarding `@babel/runtime` and `core-js` but whatever.
