### ISSUE TITLE
some tests are flaky on CI

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack-dev-server#2499]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

N/A

### Expected Behavior

Green

### Actual Behavior

Especially e2e tests aren't stable. 

### For Bugs; How can we reproduce the behavior?

See CI.

### For Features; What is the motivation and/or use-case for the feature?

Maybe the next version will be stable because I modified many tests to improve but I monitor this issue.

**Comment by hiroppy** [comment]
Let's see how it goes after migrating to github-action.

**Comment by hiroppy** [comment]
windows/node@12/webpack@next

```
FAIL test/e2e/ProvidePlugin.test.js (12.815s)
  ● ProvidePlugin › inline with transportMode.client ws › on browser client › should inject ws client implementation

    Unhandled error. (Error: Page crashed!

      at Page._onTargetCrashed (node_modules/puppeteer/lib/Page.js:287:24)
      at CDPSession.<anonymous> (node_modules/puppeteer/lib/Page.js:175:56)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:252:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:143:28)
      at WebSocket.<anonymous> (node_modules/puppeteer/lib/WebSocketTransport.js:47:42)
      at WebSocket.onMessage (node_modules/ws/lib/event-target.js:127:16)
      at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:746:20)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:428:14)
      at Receiver.getData (node_modules/ws/lib/receiver.js:360:17)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:152:22)
      at Receiver._write (node_modules/ws/lib/receiver.js:83:10)
      at Socket.socketOnData (node_modules/ws/lib/websocket.js:819:35)
```

**Comment by hiroppy** [comment]
macos/node@10/webpack@next

```
FAIL test/e2e/Iframe.test.js (22.229s)
  ● Client iframe console.log › hot disabled

    expect(received).toMatchSnapshot()

    Snapshot name: `Client iframe console.log hot disabled 1`

    - Snapshot
    + Received

    - Array [
    -   "Hey.",
    -   "[WDS] Live Reloading enabled.",
    - ]
    + Array []

      86 |         .then(() => {
      87 |           // Order doesn't matter, maybe we should improve that in future
    > 88 |           expect(res.sort()).toMatchSnapshot();
         |                              ^
      89 |           done();
      90 |         });
      91 |     });

      at toMatchSnapshot (test/e2e/Iframe.test.js:88:30)
```

**Comment by hiroppy** [comment]
windows/node@8/webpack@latest

```
FAIL test/e2e/ClientOptions.test.js (41.099s)
  ● Client code › behind a proxy › requests websocket through the proxy with proper port number

    Unhandled "error" event. (Error: Page crashed!)

      at Page._onTargetCrashed (node_modules/puppeteer/lib/Page.js:287:10)
      at CDPSession.Page.client.on.event (node_modules/puppeteer/lib/Page.js:175:56)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:252:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:143:28)
      at WebSocketTransport._ws.addEventListener.event (node_modules/puppeteer/lib/WebSocketTransport.js:47:42)
      at WebSocket.onMessage (node_modules/ws/lib/event-target.js:127:16)

```

**Comment by evilebottnawi** [comment]
> Page crashed!

Very strange :confused:

**Comment by hiroppy** [comment]
Windows has many problems...

**Comment by evilebottnawi** [comment]
@hiroppy Do you test locally?

**Comment by hiroppy** [comment]
@evilebottnawi sorry for the late reply, I can't reproduce these at my local.

**Comment by evilebottnawi** [comment]
Very very very strange, I will look at that in near future too

**Comment by hiroppy** [comment]
Yeah, and actually we just replaced azule-pilelines with github-actions, no rewriting core code...
