### ISSUE TITLE
Error when using https key and cert generated by mkcert

### ISSUE THREAD

**Issue by rightaway** [webpack/webpack-dev-server#2518]
- Operating System: linux
- Node Version:13.12
- NPM Version: yarn 1.22.4
- webpack Version: 4.42.1
- webpack-dev-server Version: 3.10.3
- Browser:

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I've got this as part of my configuration.

```
{
  devServer
    https: {
      key: "~/key.pem",
      cert: "~/cert.pem"
    }
  }
}
```

I'm getting an error when trying to start the server using a key and cert generated using my own CA generated with `mkcert`. The files exist with correct permissions and are correct because when served by nginx they work fine. For some reason webpack-dev-server is giving an error with them.

```
Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1312:27)
    at Server (_tls_wrap.js:1176:8)
    at new Server (https.js:64:14)
    at Object.createServer (https.js:88:10)
    at Server.createServer (node_modules/webpack-dev-server/lib/Server.js:664:35)
    at new Server (node_modules/webpack-dev-server/lib/Server.js:128:10)
    at startDevServer (node_modules/webpack-dev-server/bin/webpack-dev-server.js:106:14)
```

### For Bugs; How can we reproduce the behavior?

Can reproduce by running these commands then starting webpack-dev-server
```
mkcert -install
mkcert "*.example.com" -cert-file ~/cert.pem -key-file ~/key.pem
```

**Comment by chapterjason** [comment]
@rightaway the solution?
