### ISSUE TITLE
Error when try to use JSCS to lint the JS style

### ISSUE THREAD

**Issue by davegomez** [webpack/webpack-dev-server#269]
This is the error I got in the log when I try to use **JSCS** as preLoader using `webpack-dev-server`

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/dave/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart package@0.0.1
6 info start package@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info package@0.0.1 Failed to exec start script
9 verbose stack Error: package@0.0.1 start: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/dave/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/Users/dave/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid package@0.0.1
11 verbose cwd /Users/dave/Development/personal/package
12 error Darwin 14.5.0
13 error argv "node" "/Users/dave/.nvm/versions/node/v0.12.7/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error package@0.0.1 start: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the package@0.0.1 start script 'webpack-dev-server'.
18 error This is most likely a problem with the package package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls package
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

I'm using *JSCS v2.1.1*.

Also, I can't use `webpack-dev-server` with **Node v4.0.0**, moving to **BrowserSync**.

**Comment by SpaceK33z** [comment]
Do you still have this issue? Doesn't seem like it's related to webpack-dev-server.

**Comment by SpaceK33z** [comment]
I'm closing this issue because of inactivity. Feel free to comment, and we can always re-open it again.
