### ISSUE TITLE
Webpack module federation breaks with multiple entrypoints

### ISSUE THREAD

**Issue by codepunkt** [webpack/webpack-dev-server#2692]
This time it's @sokra who told me this is probably the place to open an issue.

- Operating System: Windows 10
- Node Version: 12.16.2
- NPM Version: 6.14.4
- webpack Version: 5.0.0-beta.22
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 84.0.4147.105, Firefox 79.0, Edge 84.0.522.48

- [x] This is a **bug**

### Code

https://github.com/codepunkt/module-federation-examples/tree/dynamic-host-remote

### Expected Behavior

Using `webpack-dev-server` instead of `webpack` should still support module federation with additional content tacked onto the remoteEntry by defining it as an additional `entry`.

### Actual Behavior

Running "yarn start" to start `webpack-dev-server` breaks module federation and thus breaks the app in development mode.

### For Bugs; How can we reproduce the behavior?

1. clone repository
2. ensure you're on branch "dynamic-host-remote"
2. run `yarn` on repo root
3. go into "dynamic-host-remote" directory
4. run `yarn start` in "dynamic-host-remote" directory
5. open `localhost:3001` in the browser
6. encounter an error in the browser console that happens when executing app2/remoteEntry.js with the additional contents that were added to this entrypoint by `webpack-dev-server`
7. OPTIONAL: run `yarn build && yarn serve` and revisit `localhost:3001` to see production build working just fine.

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack-dev-server

**Comment by evilebottnawi** [comment]
Feel free to send a fix

**Comment by codepunkt** [comment]
If I had a clue what the problem is, i'd send a PR right away. Spent a few hours with this, don't have the slightest idea 🤔

**Comment by ScriptedAlchemy** [comment]
Okay, so the issue here is that WDS is likely appending its own entrypoint to the array / injecting a "require" to the hmr client. That typically serves as the entry module of an application. When ModuleFederation emits a remoteEnty with the same name as the entrypoint, they are merged. 

This lets us attach initialization code, to federated remotes. something like changing publicPath. 

__webpack_public_path__ = new URL(document.currentScript.src).origin + "/";


https://github.com/module-federation/module-federation-examples/pull/277

![image](https://user-images.githubusercontent.com/25274700/89253737-4bd01d00-d5d2-11ea-8f24-be5d4a284618.png)

The remote becomes 400kb big (usually like 5kb) and the module returned to the global is not `__webpack_require__("webpack/container/entry/app1");` - therefore window.app1 will not be `__webpack_require__("webpack/container/entry/app1");` and the federated API is never set to the global

**Comment by sokra** [comment]
The wds entrypoint should be prepended instead of appended. The last value is exported.

**Comment by ScriptedAlchemy** [comment]
Will take a look, thanks @sokra

**Comment by ScriptedAlchemy** [comment]
Looks like we want to modify this

```js
 const prependEntry = (originalEntry, additionalEntries) => {
      if (typeof originalEntry === 'function') {
        return () =>
          Promise.resolve(originalEntry()).then((entry) =>
            prependEntry(entry, additionalEntries)
          );
      }

      if (typeof originalEntry === 'object' && !Array.isArray(originalEntry)) {
        /** @type {Object<string,string>} */
        const clone = {};

        Object.keys(originalEntry).forEach((key) => {
          // entry[key] should be a string here
          const entryDescription = originalEntry[key];
          if (typeof entryDescription === 'object' && entryDescription.import) {
            clone[key] = Object.assign({}, entryDescription, {
              import: prependEntry(entryDescription.import, additionalEntries),
            });
          } else {
            clone[key] = prependEntry(entryDescription, additionalEntries);
          }
        });
```

**Comment by sokra** [comment]
It already prepends... So there is somethings else wrong

**Comment by sokra** [comment]
The bug is here:

https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/utils/addEntries.js#L86-L92

Desprite the function name `prepend` it actually appends...

Change it to:

``` js
      /** @type {Entry} */
      const entriesClone = [].concat(originalEntry);
      additionalEntries.forEach((newEntry) => {
        if (!entriesClone.includes(newEntry)) {
          entriesClone.push(newEntry);
        }
      });
```

**Comment by evilebottnawi** [comment]
Great, feel free to send a PR

**Comment by snitin315** [comment]
I will send a PR.

**Comment by codepunkt** [comment]
I'm not sure this will actually fix HMR with module federation - but i'm looking forward to try!

**Comment by ScriptedAlchemy** [comment]
Opening PR, will need to work on / help on test case

**Comment by Loonride** [comment]
I looked into this more closely, and here is the full problem:

In most cases, the dev server is trying to add some variation of these 2 entries (unless you disable their injection): `webpack-dev-server/client/default/index.js` and `webpack/hot/dev-server.js`.

### Current behavior (webpack 5):

Our config has a single entry: `main.js`.

The 2 dev server entries are appended to the entry list (as explained above), resulting in something like:

```
main: {
  import: {
    'main.js',
    'webpack-dev-server/client/default/index.js',
    'webpack/hot/dev-server.js'
  }
}
```

Then we call the `entryOption` hook with all of these entries here: https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/utils/updateCompiler.js#L51

This results in an entry list on the webpack side that looks like this:
 `main.js`,  `main.js`, `webpack-dev-server/client/default/index.js`, `webpack/hot/dev-server.js`

So it would seem that prepending the 2 entries would fix the issue:
 `main.js`, `webpack-dev-server/client/default/index.js`, `webpack/hot/dev-server.js`, `main.js`

However, it is not that simple because webpack essentially filters out the duplicate entries, taking only the first of the duplicates (https://github.com/webpack/webpack/blob/bdf4a2b942bed9d78815af828f7935ddfcd3d567/lib/Compilation.js#L1764), so we get: `main.js`, `webpack-dev-server/client/default/index.js`, `webpack/hot/dev-server.js` (regardless of if we append or prepend in the webpack step).

Thus, the solution is to either change how this filtering works, or change the selection of entries by webpack such that the very first entry from the `entryOption` hook is used, rather than the very last.

I think the latter is preferred, because I realize now that it is not ideal to be pushing duplicate entries into the `entryOption` hook (as we do currently).

**Comment by sokra** [comment]
> Then we call the `entryOption` hook with all of these entries here:
> 
> https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/utils/updateCompiler.js#L51

Why does webpack-dev-server do that? The hooks is not owned by webpack-dev-server. It should not call it. It's already called by webpack itself. That's probably also the reason why the entries are added twice...

Seems like this seem to be some kind of hack to reapply the `entry` option, because it has been modified after the options has been applied, which is too late. It doesn't make sense to modify the options after they have been applied to the compiler (converted to plugin). You need to use a plugin instead.

A plugin to add these entries for webpack-dev-server could be like that:

``` js
compiler.hooks.make.tapAsync({
    name: "webpack-dev-server",
    stage: -100
}, (compilation, callback) => {
    const options = {
        name: undefined // global entry, added before all entries
    };
    const dep = EntryPlugin.createDependency("webpack-dev-server/client/...", options);
    compilation.addEntry(context, dep, options, err => {
        callback(err);
    });
});
```

Note the hack works in webpack 4 as each entrypoint can only have a single module (arrays are wrapped in a artificial module), so reapplying the entryOption also adds it twice, but the second one overrides the first one.

There is no `global entry` in webpack 4, so the above plugin doesn't work for webpack 4. I would keep the hack as legacy code, as a clean solution is more complex.

**Comment by codepunkt** [comment]
Thanks everyone for chiming in.

What confuses me a little about this is that `webpack-dev-server`, which i always thought of as a "major part of webpack", actually seems to be an afterthought when it comes to new developments.

I don't understand a lot of the details everyone wrote in this issue, but i'm glad this problem is being ironed out and fixed.

**Comment by pmmmwh** [comment]
> Note the hack works in webpack 4 as each entrypoint can only have a single module (arrays are wrapped in a artificial module), so reapplying the entryOption also adds it twice, but the second one overrides the first one.
> 
> There is no `global entry` in webpack 4, so the above plugin doesn't work for webpack 4. I would keep the hack as legacy code, as a clean solution is more complex.

@sokra is there a "correct"/"clean" way to inject global entries as a plugin (for Webpack 4)? I'm asking about this for fast-refresh in general because we need to ensure global runtime code is being setup before user code. Similar to WDS, what we're doing today is this (without the `entryOptions` hack) within `apply`:

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/utils/injectRefreshEntry.js

**Comment by MaximSagan** [comment]
Sorry to be that guy, but... any updates?

**Comment by alexander-akait** [comment]
Fully work on the next releases (included stable release) will be started on the next week

**Comment by wangmeijian** [comment]
> 下一个版本（包括稳定版本）的全部工作将在下周开始

When will it be updated?

**Comment by csvan** [comment]
> > 下一个版本（包括稳定版本）的全部工作将在下周开始
> 
> When will it be updated?

When it's done, feel free to help :)

**Comment by raix** [comment]
@alexander-akait are there anything we can help out with eg. code/test/debug etc. not sure how much is missing/done?

_(Despite visiting issues/pr's opened/closed and trying to follow things merged to master etc. I still don't have an overview on how to help out here)_

**Comment by alexander-akait** [comment]
@raix Here fix https://github.com/webpack/webpack-dev-server/pull/2920, can you try locally? I need rewrite some tests, if it will work I will focus on it and will do release, I already work on webpack-dev-server (focused on webpack-cli and webpack-dev-server, want to finish all problem to move ahead)

**Comment by robinlarsson** [comment]
@alexander-akait are there any updates around this issue? We would love to start using Module Federation and this fix of yours would be very useful. Are you still in need of testing for #2920 locally?

**Comment by csvan** [comment]
Now that #2920 is merged, I tried running with Module Federation locally, but it seems to fail here (in the entry point of the federated module):

```
function checkDeferredModulesImpl() {
    var result;
    for (var i = 0; i < deferredModules.length; i++) {
        var deferredModule = deferredModules[i];
        var fulfilled = true;
        for (var j = 1; j < deferredModule.length; j++) {
            var depId = deferredModule[j];
            if (installedChunks[depId] !== 0) fulfilled = false;
        }
        if (fulfilled) {
            deferredModules.splice(i--, 1);
            result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
        }
    }
    if (deferredModules.length === 0) {
        __webpack_require__.x();
        __webpack_require__.x = x => {
        };
    }
    return result;
}
```

The reason is that the following line will always set `fulfilled` to false, because dev-server injects its own entries into `deferredModule`: 

```
if (installedChunks[depId] !== 0) fulfilled = false;
```

Thus `result` will always be undefined.

**Comment by alexander-akait** [comment]
@csvan Can you provide example? I think we need fix it better

**Comment by csvan** [comment]
@alexander-akait not yet unfortunately, noticed it in one of our own projects when running dev-server with a Module Federation project. I could try setting a small repro up.

I wonder where this comes from though, I suppose it is added by Webpack:

```
    var deferredModules = [
      ["./node_modules/webpack-dev-server/client/default/index.js?http://0.0.0.0", "vendors-node_modules_webpack-dev-server_client_default_index_js_http_0_0_0_0-node_modules_web-394369"],
      ["webpack/container/entry/supportwidget", "vendors-node_modules_webpack-dev-server_client_default_index_js_http_0_0_0_0-node_modules_web-394369"]
    ];
```

**Comment by csvan** [comment]
@alexander-akait repro here: https://github.com/csvan/wds-mf-repro

It needs the latest version of webpack-dev-server though, the repro references the last beta

**Comment by alexander-akait** [comment]
Thanks, I will look at this in near future, the next beta will be on this week, so I try to resolve it

**Comment by csvan** [comment]
Dug a bit more, this only seems to happen when this evaluates to true during the build:

https://github.com/webpack/webpack/blob/80c5041fe1f909d34975abd33e03bdb069876ea9/lib/web/JsonpHelpers.js#L61

As long as the `checkDeferredModulesImpl` is not added to the entry point by webpack, things work well on master

**Comment by kumarlachhani** [comment]
Request @alexander-akait to help us in updating about the issue.

**Comment by alexander-akait** [comment]
It think should be fixed in `beta-1`, somebody can try?

**Comment by kumarlachhani** [comment]
Sorry for asking this again but any updates on this issue? @alexander-akait bro?

**Comment by mawi12345** [comment]
I have setup a [minimal example](https://github.com/mawi12345/module-federation-dynamic-remotes-hot) (just [module-federation dynamic-remotes](https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes) with updated dependencies) and **hot reloading is working with module federation**. Not sure if this is exactly what @codepunkt reported.

**Comment by ruanyl** [comment]
@mawi12345 I tried your examples, the hot reload works if you open the host app `http://localhost:3001/`, but it doesn't work if you open `http://localhost:3002/` directly.

The warning shows up:
```
[HMR] Update failed: ChunkLoadError: Loading hot update chunk main failed.
(missing: http://localhost:3002/main.4ad69454e89bc241f658.hot-update.js)
    at http://localhost:3002/main.js:1200:26
    at new Promise (<anonymous>)
    at loadUpdateChunk (http://localhost:3002/main.js:1195:20)
    at http://localhost:3002/main.js:1655:29
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.hmrC.jsonp (http://localhost:3002/main.js:1650:22)
    at http://localhost:3002/main.js:828:45
    at Array.reduce (<anonymous>)
    at http://localhost:3002/main.js:824:53
```

**Comment by alexander-akait** [comment]
@ruanyl Why it should work on `http://localhost:3002/`?

**Comment by mawi12345** [comment]
> @mawi12345 I tried your examples, the hot reload works if you open the host app `http://localhost:3001/`, but it doesn't work if you open `http://localhost:3002/` directly.

@ruanyl you are correct, hot reloading is not working on the standalone + remote apps only on the host app. Not sure if this issue is about hot reloading the standalone remote.

**Comment by ruanyl** [comment]
@mawi12345 

Alright, I got some findings.

The reason is the `HtmlWebpackPlugin` takes the `main` chunk and the `remoteEntry.js` chunk. If I open the app directly as a host app, `remoteEntry` is not needed.

So I configured `HtmlWebpackPlugin` to only include the main chunk, and this solved the problem:
```
      chunks: ["main"],
```
Now webpack hot works.

**Comment by ScriptedAlchemy** [comment]
Should open a bug on html webpack. Tho I thought they fixed this in their v5 of the plugin

**Comment by omkar-nath** [comment]
Hi, We are also facing this issue. When we try to inject remoteEntry.js using System.js in our index.html for dev mode, HMR stops working. If we directly inject the main.js file in index.html, it works .

**Comment by ldt1997** [comment]
> @mawi12345 I tried your examples, the hot reload works if you open the host app `http://localhost:3001/`, but it doesn't work if you open `http://localhost:3002/` directly.
> 
> The warning shows up:
> 
> ```
> [HMR] Update failed: ChunkLoadError: Loading hot update chunk main failed.
> (missing: http://localhost:3002/main.4ad69454e89bc241f658.hot-update.js)
>     at http://localhost:3002/main.js:1200:26
>     at new Promise (<anonymous>)
>     at loadUpdateChunk (http://localhost:3002/main.js:1195:20)
>     at http://localhost:3002/main.js:1655:29
>     at Array.forEach (<anonymous>)
>     at Object.__webpack_require__.hmrC.jsonp (http://localhost:3002/main.js:1650:22)
>     at http://localhost:3002/main.js:828:45
>     at Array.reduce (<anonymous>)
>     at http://localhost:3002/main.js:824:53
> ```

add `optimization: { runtimeChunk: 'single' }` works to me

**Comment by ScriptedAlchemy** [comment]
I'm coming out with a life reload plugin that kinda attempts to solve the problem. Not hot reloading but it'll refresh the change when making them to other containers

**Comment by craigmiller160** [comment]
Hi. Just chiming in. I'm using webpack 5.50.0, html-webpack-plugin 5.3.2, and webpack-dev-server 3.11.2 and I am experiencing the issue previously described. When using module federation, I get the errors from the OP. These errors only started occurring once my app was consuming at least one remote, if that helps at all. Wondering what can be done, what you might need from me to make more progress?

**Comment by tianyingchun** [comment]
HMR not working with multiple entries 
i upgrade webpack-dev-server from v4.0.0-rc.1 to v4.0.0 it will infinite loop for update.json 404.
i use "webpack": "^5.50.0",
BTW:
webpack-dev-server@4.0.0-rc.1 with webpack@^5.50.0it work fine.webpack-dev-server@4.0.0 with webpack@^5.50.0 was broken, infinite loop for update.json

**Comment by alexander-akait** [comment]
Can you provide reproducible test repo?

**Comment by tianyingchun** [comment]
1. install webpack@^5.50.0, webpack-dev-server@4.0.0  
2. configuration webpack with two entries or above
3. while start serve mode with hot configuration
```
hot: true,
      compress: true,
      open: false,
      port: mockPort,
      static: {
        directory: `${join(projectCwd, '/public')}`,
      },
      // Load https
      https: evolveOptions.https,
      // Enable firewall or set hosts that are allowed to access the dev server.
      allowedHosts: 'all',
      client: {
        overlay: {
          errors: true,
          // don't show overlay warning message in dev page, view warning mesage in console.
          warnings: false,
        },
      },
```
while page loading first it will infinite loop hot reload.

4. while update really code related one of  entry , this entry is reload that's ok
5. for single entry works fine both rc.1 and v4.0.0

Totally this issue occurs only while first loading of webpack serve.

it works ok once we have some really code modified, and triggered really dev-server `reload`

**Comment by tianyingchun** [comment]
i think in `client-src/utils/reloadApp.js` it has something broken while `dev-server` initial 
```ts
unction reloadApp({ hot, liveReload }, status) {
  if (status.isUnloading) {
    return;
  }

  // TODO Workaround for webpack v4, `__webpack_hash__` is not replaced without HotModuleReplacement plugin
  const webpackHash =
    // eslint-disable-next-line camelcase
    typeof __webpack_hash__ !== "undefined"
      ? // eslint-disable-next-line camelcase
        __webpack_hash__
      : status.previousHash || "";
  const isInitial = status.currentHash.indexOf(webpackHash) === 0;

  if (isInitial) {
    const isLegacyInitial =
      webpackHash === "" && hot === false && liveReload === true;

    if (isLegacyInitial) {
      status.previousHash = status.currentHash;
    }

    return;
  }

  function applyReload(rootWindow, intervalId) {
    clearInterval(intervalId);

    log.info("App updated. Reloading...");

    rootWindow.location.reload();
  }

  const search = self.location.search.toLowerCase();
  const allowToHot = search.indexOf("webpack-dev-server-hot=false") === -1;
  const allowToLiveReload =
    search.indexOf("webpack-dev-server-live-reload=false") === -1;

  if (hot && allowToHot) {
    log.info("App hot update...");

    hotEmitter.emit("webpackHotUpdate", status.currentHash);

    if (typeof self !== "undefined" && self.window) {
      // broadcast update to window
      self.postMessage(`webpackHotUpdate${status.currentHash}`, "*");
    }
  }

```

**Comment by alexander-akait** [comment]
I will look at this in near future, but nothing special here, you should not get infinity reload if you have `hot: true`

**Comment by tianyingchun** [comment]
i have tried, replace all `client/index.js` from `rc.1` it works fine.

**Comment by alexander-akait** [comment]
WIP

**Comment by tianyingchun** [comment]
```
  ok() {
    sendMessage("Ok");

    if (options.overlay) {
      hide();
    }

    if (options.initial) {
      return (options.initial = false);
    }

    reloadApp(options, status);
  },
```
above code while first start up webpack dev server it will always invoke `reloadApp` but it should not call `reloadApp` while first enter `ok()`

**Comment by alexander-akait** [comment]
We move `options.initial` in reloadApp, because it is break lazy compilation, it is weird check, now check inside reloadApp

**Comment by tianyingchun** [comment]
no idea, but it seems that, i can't see anything about `initial` status in `reloadApp`

**Comment by alexander-akait** [comment]
I can't reproduce your problem, please create reproducible test repo

**Comment by tianyingchun** [comment]
ok, i try to create an demo repo now. :)

**Comment by tianyingchun** [comment]
this demo i need spend some time, do you have tried for multiple webpack compiler?
@alexander-akait

**Comment by alexander-akait** [comment]
Yes, works fine everywhere, even more we have tests on this

**Comment by alexander-akait** [comment]
You can try to debug it, go to `node_modules/webpack-dev-server/client/reloadApp.js` and put `console.log(webpackHash);console.log(status)` and put logs here (don't forget preserve them in dev tools)

**Comment by tianyingchun** [comment]
webpackHash: "ee67c9096e15366640d4",
status: {isUnloading: false, currentHash: "b83ab9f474a182a21a82"}

**Comment by alexander-akait** [comment]
It is on initial run? very weird, it means somebody change your hash of build

**Comment by tianyingchun** [comment]
yes only the first initial run, while i update my code and save, it works fine.

**Comment by tianyingchun** [comment]
could you give suggestions?

**Comment by alexander-akait** [comment]
No idea, maybe non official plugin break, hash should not changed on initial run, please create reproducible test repo

**Comment by tianyingchun** [comment]
ok i have created demo repo for reproduce this issue.

**Comment by alexander-akait** [comment]
Great, can you provide a link?

**Comment by tianyingchun** [comment]
wait me moment, it seem that i can't commit github now, authentication failed.

**Comment by tianyingchun** [comment]
i have updated repo demo here please check it .
https://github.com/tianyingchun/webpack-dev-server-demo-2692

**Comment by alexander-akait** [comment]
Thanks, I will look at this in near time

**Comment by alexander-akait** [comment]
oh, you have multiple hmr with different hashes, it is weird usage, to be honestly, ideally you should run dev server on each compiler

**Comment by alexander-akait** [comment]
we plan for webpack-dev-server@4.1 implement plugin support so you will put `plugins: [new DevServer(options)]` for the each compiler

**Comment by alexander-akait** [comment]
Or use multiple entries...

**Comment by alexander-akait** [comment]
Can you clarify why do you use single dev server for multi compiler mode? What is use case? Why do not run two dev servers?

**Comment by tianyingchun** [comment]
yes, we have huge complex project with multiple `modules` in one repo,  we setup configurations to allow us start `serve` for these individual modules `one` or `more` ,because these modules is individual `SPA` application;

1. we want to startup one `server` with the same `host` && `port` like `http://localhost:5000/`
2. we attached customized middleware in `dev Server` pipeline `/pages/*`
3. we don't want to start serve for each module with different `dev server`, because it has different `access` url.
4. also has more reason, because webpack it has support multi compilers, i think `dev-server` should support we pass multi `compilers` with `hot`

**Comment by tianyingchun** [comment]
> we plan for webpack-dev-server@4.1 implement plugin support so you will put `plugins: [new DevServer(options)]` for the each compiler

for this, do `dev-server` start only `one ` or multi dev server for multi modules?

**Comment by alexander-akait** [comment]
> also has more reason, because webpack it has support multi compilers, i think dev-server should support we pass multi compilers with hot

Sorry, it is impossible by design, you can't have the same HMR code for multi compilers, it is invalid and weird, before you don't have bug due our invalid logic for initial, in fact you should have gotten this problem much earlier, we support multi compiler mode, but your case has multiple independent builds with the same HMR, even more new features like `lazyCompilation`, buildless mode (future) will not work too

**Comment by alexander-akait** [comment]
Even more, you have only on web socket connection, therefore hash from one build will be already rewrite hash from other build, in theory we can pass unique name of compiler and implement multiple statuses, but it is more work then you think, also many plugin can break your HMR

**Comment by alexander-akait** [comment]
> yes, we have huge complex project with multiple modules in one repo, we setup configurations to allow us start serve for these individual modules one or more ,because these modules is individual SPA application;

in this case you should use multi entry mode (it will optimize your code even better) or module federation

**Comment by tianyingchun** [comment]
ok, i have rewrite my codebase to startup multi dev-server with multi `port` and dynamic organize them into express server `page proxy`.

BTW it seems that we can't disabled logger.info() message via `dev-server` config, or webpack `stats`.logging= false.

**Comment by tianyingchun** [comment]
And does  `webpack-dev-server` provider @types  for v4.0.0?

**Comment by snitin315** [comment]
> And does `webpack-dev-server` provider @types for v4.0.0?

No, but it is in our roadmap.

**Comment by alexander-akait** [comment]
@tianyingchun for logger we have the special option https://webpack.js.org/configuration/other-options/#level, we decide don't have a lot of different logger options as were before and focus only on one

**Comment by IgorStetsiuk** [comment]
This time I'll be that guy... do we have any updates on this? 

Have one question regarding Hot Module Replacement. Seems it doesn’t work properly. I used CRA with react-scripts v 5.0.0 And CRACO  to override the webpack config in order to set up my module federation and that’s everything is fine (build, test, start commands)… Thought when it comes to the local development I need manually hard reload pages to reflect changes, and it’s really inconvenient. 
 
I'm thinking to build React app from a scratch and playing around with webpack config but that is not what I wanted to do as we already have a pretty well config provided by CRA only need to override it for Module Federation config is that correct? 

Does somebody know whether CRA (latest version 5) is able to work with hot module reload? What configuration do I miss?
Thank you!

**Comment by ScriptedAlchemy** [comment]
> This time I'll be that guy... do we have any updates on this? 
> 
> 
> 
> Have one question regarding Hot Module Replacement. Seems it doesn’t work properly. I used CRA with react-scripts v 5.0.0 and CRACO  to override the webpack config in order to set up my module federation and that’s everything is fine (build, test, start commands)… Thought when it comes to the local development I need manually hard reload pages to reflect changes, and it’s really inconvenient. 
> 
>  
> 
> I'm thinking to build React app from a scratch and playing around with webpack config but that is not what I wanted to do as we already have a pretty well config provided by CRA only need to override it for Module Federation config is that correct? 
> 
> 
> 
> Does somebody know whether CRA (latest version 5) is able to work with hot module reload? What configuration do I miss?
> 
> Thank you! 

This is a very hard problem to solve. An easy workaround I use is I'll fetch all remote urls on a poll and hash them. If any hash based on the contents changes, I window reload the page. Simple but easy way to get live reloading. 

HMR is not easy since webpack needs to know both where something exists and where it's consumed. All graphs would need to be interlinked

**Comment by IgorStetsiuk** [comment]
@ScriptedAlchemy Hello! Thank you for your reply. Wouldn't you mind sharing a piece of that config where you "fetch all remote URLs on a poll and hash them"? I'm not super aware of how to set up such config in webpack and it sounds a bit difficult to me to implement that so maybe some samples would be really helpful to me to understand that configuration and make live reloading in my case. Thank you again!

**Comment by ScriptedAlchemy** [comment]
Fetch(jsUrl).then(text).then(md5hashFronString) 

Store it on some object and put the fetch in a setInterval.

**Comment by rzkhosroshahi** [comment]
Is there any temporary solution to solve the HMR issue?

**Comment by xujie-phper** [comment]
any updates, i face the same issue when use module federation

**Comment by rdenman** [comment]
Since this issue is still open, I'll link to my (pretty damn hacky) "solution" I posted in another thread: https://github.com/webpack/webpack/issues/11240#issuecomment-1505935214

It's very far from perfect, but it does the job in a pinch

**Comment by ssuvorov** [comment]
20 October 2023 👀

**Comment by ScriptedAlchemy** [comment]
Correct. The issue is collision in the runtime. Loading the remote of the hot binds to the second chunk loading global and the host no longer gets the refresh updates

**Comment by ScriptedAlchemy** [comment]
Note. Federation v2 supports hmr and faster refresh of remotes as well. 
Module-federation.io

**Comment by alexander-akait** [comment]
@ScriptedAlchemy can you point how do you resolve it?

**Comment by ScriptedAlchemy** [comment]
Which issue?

**Comment by Anubhab2003** [comment]
Hey I am Interested in contributing this issue, How to get started ?

**Comment by csvan** [comment]
@ScriptedAlchemy sorry if this is OT, but would would the v2 webpack plugin be considered a drop-in replacement for the one currently bundled with webpack itself?

**Comment by ScriptedAlchemy** [comment]
Yes

**Comment by BilalAhmedMalik1** [comment]
Try setting publicPath: "auto" in your webpack.config.js. This helps Webpack resolve URLs correctly when using webpack-dev-server, preventing issues with remoteEntry.js.

How to do it:
In your webpack.config.js, update the output section like this:


output: {
  publicPath: "auto", // Ensures correct URL resolution
}


This worked for me and might help others facing the same issue. Let me know if it helps or if there's another workaround! 😊

**Comment by Jeston10** [comment]
I want to work on this issue? How may i get started? May I work on it @ branch moderators?
