### ISSUE TITLE
TypeError: Cannot read property 'plugins' of undefined node_modules/webpack-dev-server/lib/utils/updateCompiler.js:14:19

### ISSUE THREAD

**Issue by andersonbosa** [webpack/webpack-dev-server#2751]
- Operating System: Linux kali 5.8.0-kali1-amd64 #1 SMP Debian 5.8.7-1kali1 (2020-09-14) x86_64 GNU/Linux
- Node Version: v10.20.1
- NPM Version: v6.14.4
- webpack Version: ^4.44.2
- webpack-dev-server Version: ^3.11.0
- Browser: chrome

- ### [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// cli.js
#!/usr/bin/env node

// https://github.com/webpack/webpack-dev-middleware
const webpack = require('webpack')
const WebpackDevServer = require('webpack-dev-server')
//const webpackConfiguration = require('./webpack/webpack.config')
//const args = (process.argv && process.argv.length > 2) ? process.argv.slice(2) : []
//const mode = args.length > 0 ? args[0] : 'development'
//const config = webpackConfiguration(mode)
const { rootResolve } = require('./webpack/utils')
const devserverConfig = {
    contentBase: 'dist',
    contentBasePublicPath: '/dist',
    publicPath: '/',
    host: 'localhost',
    port: 8080,
    disableHostCheck: true,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
    },
    clientLogLevel: 'warn',
    overlay: { warnings: true, errors: true },
    compress: true,
    noInfo: false,
    quiet: false,
    open: true,
    hot: true
  }
const testConfig = {
  entry: `${__dirname}/test.js`,
  output: {
    path: rootResolve(`${__dirname}/../dist`),
    filename: 'bundle.js'
  }
}
console.log(test)
new WebpackDevServer(testConfig, devserverConfig)
  .listen(
    8080,
    'localhost',
    function devserverCallback(err) {
      if (err) console.log(err)
      console.log('Listening at localhost:8080')
    })

```

```js
// my original conf is much complex but get same error
// webpack.config.js
const testConfig = {
  entry: `${__dirname}/test.js`,
  output: {
    path: rootResolve(`${__dirname}/../dist`),
    filename: 'bundle.js'
  }
}
```

```js
// additional code, remove if not needed.
```

### Actual Behavior
```
➜  default git:(feat/extract-boilerplate) ✗ suite-cli
{ entry: '/home/n3o/workspace/dev/suite/suite-builder/src/test.js',
  output:
   { path:
      '/home/n3o/workspace/dev/suite/default/home/n3o/workspace/dev/suite/suite-builder/dist',
     filename: 'bundle.js' } }
/home/n3o/workspace/dev/suite/suite-builder/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:14
      if (!config.plugins) {
                  ^

TypeError: Cannot read property 'plugins' of undefined
    at findHMRPlugin (/home/n3o/workspace/dev/suite/suite-builder/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:14:19)
    at updateCompiler (/home/n3o/workspace/dev/suite/suite-builder/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:38:12)
    at new Server (/home/n3o/workspace/dev/suite/suite-builder/node_modules/webpack-dev-server/lib/Server.js:72:5)
    at Object.<anonymous> (/home/n3o/workspace/dev/suite/suite-builder/src/cli.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by evilebottnawi** [comment]
Please fill out all fields of the issue template,I can't help you without reproducible test rep;o

**Comment by evilebottnawi** [comment]
Maybe bug in `suite-builder` side

**Comment by evilebottnawi** [comment]
You need to `WebpackDevServer` compiler, not configuration, example https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js

**Comment by andersonbosa** [comment]
thanks @evilebottnawi !I was checking the [simple example](https://github.com/webpack/webpack-dev-server/blob/master/examples/api/simple/server.js) and I realized that.
