### ISSUE TITLE
Unexpected HMR behaviour with multiple entries all loaded in one HTML page.

### ISSUE THREAD

**Issue by MohsenElgendy** [webpack/webpack-dev-server#2823]
- Operating System: macOS v10.15.6
- Node Version: v10.17.0
- NPM Version: v6.11.3
- webpack Version: v5.4.0
- webpack-dev-server Version: v3.11.0
- Browser: Google Chrome v86.0.4240.183

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports = {
    mode: 'development',
    devtool: 'eval-source-map',
    target: "web",
    entry: {
        bundle1: ['./src/script1.js'],
        bundle2: ['./src/script2.js'],
        bundle3: ['./src/script3.js'],
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'My App',
        })
    ],
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
        hot: true,
        port: 9090
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].js'
    }
};
```

```js
// ./src/script1.js
console.log('script 1');

// ./src/script2.js
console.log('script 2');

// ./src/script3.js
console.log('script 3');
```

### Expected Behavior

> all bundles are loaded in one page.

- Updating any of `script1.js`, `script2.js` or `script3.js` would accordingly hot replace that exact module. 
- the WDS should be initiated only once, but instead, because there are 3 bundles in this example, thus it is initiated 3 times.
- only changed bundles should trigger hot replacement events. 

### Actual Behavior

- the WDS is initiated x times the bundles in the `webpack.config.js`
```
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.
...
```
- updating `./src/script2.js` won't work with the following warnings in the DevTools console:
```
[HMR] Update failed: ChunkLoadError: Loading hot update chunk bundle1 failed.
(missing: http://localhost:9090/bundle1.5e1d1b20aea27554f1a0.hot-update.js)
    at http://localhost:9090/bundle1.js:1034:26
    ...

[HMR] Update failed: ChunkLoadError: Loading hot update chunk bundle2 failed.
(missing: http://localhost:9090/bundle2.5e1d1b20aea27554f1a0.hot-update.js)
    at http://localhost:9090/bundle2.js:1034:26
    ...

[HMR] Updated modules:
[HMR]  - ./src/script2.js
[HMR] App is up to date.
```

> the warnings in the console indicate that the `hot-update.js` file is missing, even though manually opening these URLs works fine.

### For Bugs; How can we reproduce the behavior?

- Run the following with the `webpack.config.js` posted above:
```
$ webpack serve --mode development --env development
```
- Navigate to the /index.html generated via the HtmlWebpackPlugin with all bundles loaded.
- Check the DevTools console and attempt to update `script2.js`

**Comment by MohsenElgendy** [comment]
```
optimization.runtimeChunk: "single"
```
Fixes the problem.
