### ISSUE TITLE
v4.0.0-beta.0: dev server fails in multiple configs env with proxy property.

### ISSUE THREAD

**Issue by sprilukin** [webpack/webpack-dev-server#2891]
- Operating System: `OSX 10.14.6`
- Node Version: `v14.15.1`
- NPM Version: `6.14.8`
- webpack Version: `5.9.0`
- webpack-dev-server Version: `v4.0.0-beta.0`
- Browser: any

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

checkout repo: `git@github.com:sprilukin/webpack-dev-server-beta4-proxy-issue.git`
or use these code snippets:

```js
// webpack.config.js
module.exports = [
    {
        entry: {
            'entry1': './src/entry1'
        },
        devServer: {
            proxy: {
                '*': {
                    target: "http://localhost:8080",
                    bypass: function (req) {
                        return req.url;
                    }
                }
            }
        }
    },
    {
        entry: {
            'entry2': './src/entry2'
        }
    }
];

```

```js
// ./src/entry1
console.log("Entry 1");
```

```js
// ./src/entry2
console.log("Entry 2");
```

### Expected Behavior
dev server started successfully

### Actual Behavior
There is an error in the console during starting dev server:

```
(node:8289) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'level' of undefined
    at /Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:203:57
    at Array.map (<anonymous>)
    at Server.setupProxyFeature (/Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:169:62)
    at Object.proxy (/Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:369:16)
    at /Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:449:24
    at Array.forEach (<anonymous>)
    at Server.setupFeatures (/Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:448:22)
    at new Server (/Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/webpack-dev-server/lib/Server.js:68:10)
    at /Users/sergey/work/my/js/webpack-dev-server-proxy-issue/node_modules/@webpack-cli/serve/lib/startDevServer.js:34:24
    at Array.forEach (<anonymous>)

```

### For Bugs; How can we reproduce the behavior?
- chekcout this repo `git@github.com:sprilukin/webpack-dev-server-beta4-proxy-issue.git`
- `npm install && npm run start`

Here is the piece of code where exception is actually thrown:
```js
          proxyOptions.logLevel = getLogLevelForProxy(
            this.compiler.options.infrastructureLogging.level
          );
```

Here `this.compiler.options` is an Array, not an Object in case of multiple webpack config env.

**Comment by alexander-akait** [comment]
Yep, bug

**Comment by sethomas** [comment]
https://github.com/webpack/webpack-dev-server/commit/b0161e9852cdf41730e82aa43efe7e88f44a4f9d#r44676178

**Comment by phaberest** [comment]
I still get the same issue, is this fix been tagged?
