### ISSUE TITLE
Breaks after 3 errors, EADDRINUSE

### ISSUE THREAD

**Issue by rottmann** [webpack/webpack-dev-server#290]
If i save a file with errors 3 times, after the 3rd save the server breaks but listening port is still in use.

Start the dev server with the expected error:
```
npm run dev
...
ERROR in ./src/services/auth.js
Module build failed: SyntaxError: /home/rottmann/git/myproject/src/services/auth.js: Unexpected token (21:4)
  19 |             }
  20 |         });*/
> 21 |     }
     |     ^
  22 | 
  23 |     getToken() {
  24 |         return localStorage.token;
    at Parser.pp.raise (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExprAtom (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
    at Parser.parseExprAtom (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExpression (/home/rottmann/git/myproject/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:79:19)
 @ ./src/routes.js 15:20-46
webpack: bundle is now VALID.
```

Then i did not change anything, only save the file again.
Build starts again and show the same error as above. (logically)

Did not change anything, only save the file again.
Build starts again and show the same error as above.

Did not change anything, only save the file again.
__Build starts again and show the same error as above but webpack end, i can see the cursor in command line:__
```
...
 @ ./src/routes.js 15:20-46
webpack: bundle is now VALID.
rottmann@computer ~/git/myproject $ _
```

Try to restart the dev server:
```
npm run dev

> myproject@1.0.0 dev /home/rottmann/git/myproject
> node ./node_modules/better-npm-run dev

running better-npm-run in /home/rottmann/git/myproject
Executing script: dev

to be executed:NODE_ENV=development webpack-dev-server --config ./webpack.config.dev.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

But i am nut sure where the problem is (node? webpack? dev server? babel? other module? my conf?)

__My conf:__

node 4.1.2

package.json
```json
{
  "name": "myproject",
  "version": "1.0.0",
  "private": true,
  "description": "Some desription",
  "main": "index.js",
  "scripts": {
    "dev": "node ./node_modules/better-npm-run dev"
  },
  "betterScripts": {
    "dev": {
      "command": "webpack-dev-server --config ./webpack.config.dev.js",
      "env": {
        "NODE_ENV": "development"
      }
    }
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "babel-plugin-react-transform": "^1.1.1",
    "better-npm-run": "0.0.2",
    "chai": "^3.3.0",
    "chai-immutable": "^1.3.0",
    "css-loader": "^0.19.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "jsdom": "^6.5.1",
    "mocha": "^2.3.3",
    "node-sass": "^3.3.3",
    "npm-check-updates": "^2.3.0",
    "react-hot-loader": "^1.3.0",
    "react-transform-hmr": "^1.0.1",
    "redux-devtools": "^2.1.5",
    "sass-loader": "^3.0.0",
    "style-loader": "^0.12.4",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.0",
    "webpack-merge": "^0.2.0"
  },
  "dependencies": {
    "classnames": "^2.1.5",
    "history": "^1.12.2",
    "immutable": "^3.7.5",
    "invariant": "^2.1.1",
    "object-assign": "^4.0.1",
    "react": "^0.14.0-rc1",
    "react-addons-pure-render-mixin": "^0.14.0-rc1",
    "react-dom": "^0.14.0-rc1",
    "react-redux": "^3.1.0",
    "react-router": "^1.0.0-rc1",
    "redux": "^3.0.2",
    "socket.io-client": "^1.3.7",
    "uuid": "^2.0.1"
  }
}
```

webpack.config.dev.js
```js
var merge = require('webpack-merge');
var path = require('path');
var webpack = require('webpack');

var config = require('./webpack.config.base');

var baseDir = __dirname;
var srcDir = path.resolve(baseDir, 'src');

module.exports = merge(config, {
    devtool: 'eval-source-map',
    entry: {
        app: [
            'webpack-dev-server/client?http://localhost:8080',
            'webpack/hot/only-dev-server'
        ]
    },
    module: {
        loaders: [{
            test: /\.js$/,
            include: [ srcDir ],
            loaders: [ 'react-hot', 'babel' ]
        }, {
            test: /\.scss$/,
            include: [ srcDir ],
            loaders: [ 'style', 'css', 'sass', 'autoprefixer?browsers=last 2 versions' ]
        }]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ],
    devServer: {
        contentBase: path.resolve(baseDir, 'static'),
        historyApiFallback: true,
        inline: true,
        progress: true,
        hot: true,
        quiet: false,
        noInfo: false,
        lazy: false,
        watchOptions: {
            aggregateTimeout : 200,
            poll: true
        },
        publicPath: config.output.publicPath,
        stats: {
            colors: true
        },
    }
});
```

webpack.config.base.js
```js
var fs = require('fs');
var path = require('path');
var webpack = require('webpack');

var baseDir = __dirname;
var srcDir = path.resolve(baseDir, 'src');

var appLibs = [ './index' ];
var packageJson = JSON.parse( fs.readFileSync( path.resolve(baseDir, 'package.json'), 'utf8') );
var vendorLibs = Object.keys(packageJson.dependencies);

module.exports = {
    context: srcDir,
    devtool: 'eval',
    entry: {
        app: appLibs,
        vendor: vendorLibs,
    },
    module: {
        loaders: [],
        noParse: [
            path.resolve(baseDir, 'node_modules/react/dist/react-with-addons.js')
        ]
    },
    resolve: {
        extensions: ['', '.js']
   },
    output: {
        path             : path.resolve(baseDir, 'build'),
        filename         : '[name].js',
        chunkFilename    : '[id].bundle.js',
        sourceMapFilename: '[file].map',
        pathinfo         : true,
        publicPath       : '/'
    },
    plugins: [
        new webpack.DefinePlugin({
            __DEV__      : process.env.NODE_ENV === 'development' ? true : false,
            __PROD__     : process.env.NODE_ENV === 'production'  ? true : false
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: Infinity
        }),
        new webpack.NoErrorsPlugin()
    ]
};
```

Have to kill the webpack-dev-server process to start a new dev server.

**Comment by rottmann** [comment]
Seems to be a problem of better-npm-run problem.

**Comment by FrenchBen** [comment]
anyway to get a flag for killing an existing webpack-dev-server? Aka if you're trying to start one, and a matching PID in the local folder exists, then kill it and start the new one?
