### ISSUE TITLE
Cant use yarn start because module is not found

### ISSUE THREAD

**Issue by thijsrijkers** [webpack/webpack-dev-server#2967]
- Operating System: Windows 10
- Node Version: v12.14.1
- NPM Version: 6.14.11
- webpack Version: newest
- webpack-dev-server Version: newest
- Browser: Google chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
    resolve:{
        modules:[path.resolve(__dirname, 'src'), 'node_modules'],
        extensions: ['.tsx', '.ts', '.jsx', '.js']
    },
    entry: ['./src/index.tsx'],
    module: {
        rules: [
            {
                test: /\.ts[x]?$/,
                exclude: /node_modules/,
                use: ['babel-loader']
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            }
        ]
    },
    output: {
        filename: '[name].js',
        chunkFilename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/'
    },
    devServer: {
        contentBase: path.join(__dirname, 'public'),
        hot: true,
        inline: true,
        historyApiFallback: true
    },
    plugins: [
        new CopyWebpackPlugin([
            {
                from: 'public',
                to: '.',
                ignore: ['README']
            }
        ]),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, 'public', 'index.html'),
            filename: 'index.html'
        })
    ]
};
```

### Expected Behavior
It launches my code when started so i can use localhost to view my site

### Actual Behavior
Getting this error:
```
PS D:\!!!!!!!!!!NovelLIB> yarn start
yarn run v1.22.5
$ webpack-dev-server --hot --config webpack.config.js --mode development
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- D:\NovelLIB\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\NovelLIB\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\NovelLIB\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by snitin315** [comment]
Change your start script to following - 

`webpack serve --hot --mode development`

**Comment by thijsrijkers** [comment]
> Change your `start` script to following -
> 
> `webpack serve --hot --mode development`

It did more but now I get this error 

```
PS D:\!!!!!!!!!!NovelLIB> yarn start
yarn run v1.22.5
$ webpack serve --hot --mode development
[webpack-cli] Failed to load 'D:\!!!!!!!!!!NovelLIB\webpack.config.js'
[webpack-cli] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, toType?, force?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (D:\!!!!!!!!!!NovelLIB\node_modules\schema-utils\dist\validate.js:104:11)
    at new CopyPlugin (D:\!!!!!!!!!!NovelLIB\node_modules\copy-webpack-plugin\dist\index.js:40:31)
    at Object.<anonymous> (D:\!!!!!!!!!!NovelLIB\webpack.config.js:37:9)
    at Module._compile (D:\!!!!!!!!!!NovelLIB\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (D:\!!!!!!!!!!NovelLIB\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadConfig (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:753:31) {
  name: 'ValidationError',
  errors: [
    {
      keyword: 'required',
      dataPath: '[0]',
      schemaPath: '#/required',
      params: [Object],
      message: "should have required property 'patterns'",
      schema: [Object],
      parentSchema: [Object],
      data: [Object],
      children: [Array]
    }
  schema: {
    definitions: { ObjectPattern: [Object], StringPattern: [Object] },
    type: 'object',
    additionalProperties: false,
    properties: { patterns: [Object], options: [Object] },
    required: [ 'patterns' ]
  },
  headerName: 'Copy Plugin',
  baseDataPath: 'options',
  postFormatter: null,
  message: 'Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.\n' +
    " - options[0] misses the property 'patterns'. Should be:\n" +
    '   [non-empty string | object { from, to?, context?, globOptions?, filter?, toType?, force?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by snitin315** [comment]
Validation error , your webpack config needs to be updated as per latest schema.

**Comment by thijsrijkers** [comment]
> Validation error , your config for copy plugin needs to be updated as per latest schema.

I added my code because I saw that I was using the old syntax
```
new CopyWebpackPlugin({
            patterns:[
                {
                    from: 'public',
                    to: '.',
                    ignore: ['README']
                }
            ]
        }),
      ```
 But now I get this error:
 ```
 [webpack-cli] Failed to load 'D:\!!!!!!!!!!NovelLIB\webpack.config.js'
[webpack-cli] ValidationError: CopyPlugin Invalid Options

options should be array

    at validateOptions (D:\!!!!!!!!!!NovelLIB\node_modules\copy-webpack-plugin\node_modules\schema-utils\src\validateOptions.js:32:11)
    at new CopyPlugin (D:\!!!!!!!!!!NovelLIB\node_modules\copy-webpack-plugin\dist\index.js:26:30)
    at Object.<anonymous> (D:\!!!!!!!!!!NovelLIB\webpack.config.js:37:9)
    at Module._compile (D:\!!!!!!!!!!NovelLIB\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (D:\!!!!!!!!!!NovelLIB\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadConfig (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:753:31)
    at WebpackCLI.resolveConfig (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:867:44)
    at WebpackCLI.createCompiler (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:1157:33)
    at Command.<anonymous> (D:\!!!!!!!!!!NovelLIB\node_modules\@webpack-cli\serve\lib\index.js:65:40)
    at Command.listener [as _actionHandler] (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:953:18)
    at Command._parseCommand (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:970:12)
    at Command.parse (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:801:10)
    at Command.parseAsync (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\node_modules\commander\index.js:828:10)
    at Command.<anonymous> (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:708:32)
    at async Promise.all (index 0)
    at async WebpackCLI.run (D:\!!!!!!!!!!NovelLIB\node_modules\webpack-cli\lib\webpack-cli.js:711:9) {
  name: 'ValidationError',
  message: 'CopyPlugin Invalid Options\n\noptions should be array\n',
  errors: [
    {
      keyword: 'type',
      dataPath: '',
      schemaPath: '#/type',
      params: [Object],
      message: 'should be array'
    }
  ]
}
 ```
 
 Idk if it is to much asked but do you have a example of implementation?

**Comment by alexander-akait** [comment]
Please update copy-webpack-plugin to the latest version

**Comment by Andrey-Bushman** [comment]
I have the same bug.

Operating System: Windows 10
Node Version: v14.15.1
NPM Version: 6.14.8
"webpack": "^5.17.0"
"webpack-cli": "^4.4.0",
"webpack-dev-server": "^3.11.2"
Browser: Google chrome

My script in the *package.json* file:
`"start": "npx webpack-dev-server --mode development --open"`

Error message:
> Error: Cannot find module 'webpack-cli/bin/config-yargs'
