### ISSUE TITLE
webpack5: devserver does not work with --cacert CLI option 

### ISSUE THREAD

**Issue by rytnkmr** [webpack/webpack-dev-server#2996]
- Operating System: macOS Catalina 10.15.7
- Node Version: 10.15.7
- NPM Version: 7.5.2
- webpack Version: 5.21.1
- webpack-dev-server Version: 3.11.2
- Browser: -

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  mode: 'development',
  plugins: [new webpack.ProgressPlugin(), new HtmlWebpackPlugin({
            template: 'index.html'
          })],
  module: {
    rules: []
  },
  devServer: {
    open: true,
    host: 'localhost'
  }
}
```

### Expected Behavior
dev-server is served and cacert.pem is used

### Actual Behavior
![image](https://user-images.githubusercontent.com/38753657/107116548-563bde00-68b7-11eb-8d0c-94d97eea9932.png)

log is below:
```log
0 verbose cli [
0 verbose cli   '/Users/rytnkmr/.nodebrew/node/v14.15.4/bin/node',
0 verbose cli   '/Users/rytnkmr/.nodebrew/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'webpack',
0 verbose cli   'serve',
0 verbose cli   '--https',
0 verbose cli   '--cert',
0 verbose cli   'localhost.crt',
0 verbose cli   '--key',
0 verbose cli   'localhost.key',
0 verbose cli   '--cacert',
0 verbose cli   'cacert.pem'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 0ms
4 timing config:load:file:/Users/rytnkmr/.nodebrew/node/v14.15.4/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/rytnkmr/dev/experiments/myproject/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/rytnkmr/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/Users/rytnkmr/.nodebrew/node/v14.15.4/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 verbose npm-session b0d13c6ffd6bd81f
20 timing npm:load Completed in 11ms
21 timing command:exec Completed in 806ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/rytnkmr/.nodebrew/node/v14.15.4/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid my-webpack-project@1.0.0
24 verbose cwd /Users/rytnkmr/dev/experiments/myproject
25 verbose Darwin 19.6.0
26 verbose argv "/Users/rytnkmr/.nodebrew/node/v14.15.4/bin/node" "/Users/rytnkmr/.nodebrew/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "webpack" "serve" "--https" "--cert" "localhost.crt" "--key" "localhost.key" "--cacert" "cacert.pem"
27 verbose node v14.15.4
28 verbose npm  v7.5.2
29 error code 2
30 error path /Users/rytnkmr/dev/experiments/myproject
31 error command failed
32 error command sh -c webpack "serve" "--https" "--cert" "localhost.crt" "--key" "localhost.key" "--cacert" "cacert.pem"
33 verbose exit 2
```

I added `devServer.ca` property in the configuration file  and tried without `--cacert` option, then it works.
```js
// webpack.config.js
  devServer: {
    ca: 'cacert.pem', // add
    open: true,
    host: 'localhost'
  }
```
```zsh
npx webpack serve --https --cert localhost.crt --key localhost.key
```
### For Bugs; How can we reproduce the behavior?
start devServer with `--cacert` option
```zsh
npx webpack serve --https --cert [path to cert] --key [path to key] --cacert [path to cacert]
```

**Comment by snitin315** [comment]
Are you using the latest version of `webpack-cli`?

**Comment by rytnkmr** [comment]
> Are you using the latest version of `webpack-cli`?

@snitin315 
Yes, my `webpack-cli` is of version 4.5.0

**Comment by alexander-akait** [comment]
@rytnkmr can you run `webpack serve --help`?

**Comment by rytnkmr** [comment]
> @rytnkmr can you run `webpack serve --help`?

@alexander-akait 
here is the result

```
Usage: webpack [entries...] [options]
Alternative usage to run commands: webpack [command] [options]

The build tool for modern web applications.

Options:
  -c, --config <value...>                Provide path to a webpack configuration file e.g. ./webpack.config.js.
  --config-name <value...>               Name of the configuration to use.
  -m, --merge                            Merge two or more configurations using 'webpack-merge'.
  --env <value...>                       Environment passed to the configuration when it is a function.
  --progress [value]                     Print compilation progress during build.
  -j, --json [value]                     Prints result as JSON or store it in a file.
  -d, --devtool <value>                  Determine source maps to use.
  --no-devtool                           Do not generate source maps.
  --entry <value...>                     The entry point(s) of your application e.g. ./src/main.js.
  --mode <value>                         Defines the mode to pass to webpack.
  --name <value>                         Name of the configuration. Used when loading multiple configurations.
  -o, --output-path <value>              Output location of the file generated by webpack e.g. ./dist/.
  --stats [value]                        It instructs webpack on how to treat the stats e.g. verbose.
  --no-stats                             Disable stats output.
  -t, --target <value...>                Sets the build target e.g. node.
  -w, --watch                            Watch for files changes.
  --no-watch                             Do not watch for file changes.
  --watch-options-stdin                  Stop watching when stdin stream has ended.
  --no-watch-options-stdin               Do not stop watching when stdin stream has ended.

Global options:
  --color                                Enable colors on console.
  --no-color                             Disable colors on console.
  -v, --version                          Output the version number of 'webpack', 'webpack-cli' and
                                         'webpack-dev-server' and commands.
  -h, --help [verbose]                   Display help for commands and options.

Commands:
  build|bundle|b [entries...] [options]  Run webpack (default command, can be omitted).
  configtest|t [config-path]             Validate a webpack configuration.
  help|h [command] [option]              Display help for commands and options.
  info|i [options]                       Outputs information about your system.
  init|c [scaffold...] [options]         Initialize a new webpack configuration.
  loader|l [output-path]                 Scaffold a loader.
  plugin|p [output-path]                 Scaffold a plugin.
  serve|s [entries...] [options]         Run the webpack dev server.
  version|v [commands...]                Output the version number of 'webpack', 'webpack-cli' and
                                         'webpack-dev-server' and commands.
  watch|w [entries...] [options]         Run webpack and watch for files changes.

To see list of all supported commands and options run 'webpack --help=verbose'.

Webpack documentation: https://webpack.js.org/.
CLI documentation: https://webpack.js.org/api/cli/.
Made with ♥ by the webpack team.
```

**Comment by rytnkmr** [comment]
@alexander-akait 
sorry, I made a mistake. here is the result of `webpack serve --help`
```
Usage: webpack serve|s [entries...] [options]

Run the webpack dev server.

Options:
  -c, --config <value...>     Provide path to a webpack configuration file e.g. ./webpack.config.js.
  --config-name <value...>    Name of the configuration to use.
  -m, --merge                 Merge two or more configurations using 'webpack-merge'.
  --env <value...>            Environment passed to the configuration when it is a function.
  --progress [value]          Print compilation progress during build.
  -j, --json [value]          Prints result as JSON or store it in a file.
  -d, --devtool <value>       Determine source maps to use.
  --no-devtool                Do not generate source maps.
  --entry <value...>          The entry point(s) of your application e.g. ./src/main.js.
  --mode <value>              Defines the mode to pass to webpack.
  --name <value>              Name of the configuration. Used when loading multiple configurations.
  -o, --output-path <value>   Output location of the file generated by webpack e.g. ./dist/.
  --stats [value]             It instructs webpack on how to treat the stats e.g. verbose.
  --no-stats                  Disable stats output.
  -t, --target <value...>     Sets the build target e.g. node.
  --watch-options-stdin       Stop watching when stdin stream has ended.
  --no-watch-options-stdin    Do not stop watching when stdin stream has ended.
  --bonjour                   Broadcasts the server via ZeroConf networking on start
  --lazy                      Lazy
  --liveReload                Enables/Disables live reloading on changing files
  --serveIndex                Enables/Disables serveIndex middleware
  --inline                    Inline mode (set to false to disable including client scripts like livereload)
  --progress                  Print compilation progress in percentage
  --hot-only                  Do not refresh page if HMR fails
  --stdin                     close when stdin ends
  --open [value]              Open the default browser, or optionally specify a browser name
  --useLocalIp                Open default browser with local IP
  --open-page <value>         Open default browser with the specified page
  --client-log-level <value>  L
```

**Comment by alexander-akait** [comment]
As you can see no the `cacert` option

**Comment by rytnkmr** [comment]
@alexander-akait 
There was missing lines, so I pasted the result again in the previous comment.
There is the `--cacert` option.

**Comment by alexander-akait** [comment]
I will look at this in near future
