### ISSUE TITLE
Cannot run here.

### ISSUE THREAD

**Issue by 368573607** [webpack/webpack-dev-server#3003]
- Operating System: Windows 10
- Node Version: v14.4.0
- NPM Version: v7.5.1
- webpack Version: 5.21.2
- webpack-dev-server Version: 3.11.2
- Browser: Chrome - Dev 89.0.4385.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
//const HtmlWebpackInlineSourcePlugin = require("html-webpack-inline-source-plugin");

module.exports = {
    entry: "./src/index.js",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "[name].js"
    },
    mode: "production",
    module: {
        rules: [
            {
                test: /\.m?jsx?$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                    options: {
                        babelrc: false,
                        presets: [
                            "@babel/preset-react",
                            ["@babel/preset-env", {
                                "targets": {
                                    "chrome": 70
                                },
                                "useBuiltIns": "usage",
                                "corejs": 3
                            }]
                        ]
                    }
                }
            }, {
                test: /\.(png|jpg|svg|gif)$/,
                use: "asset/inline"
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: "./src/html/template.html",
            filename: "index.html"
        })
    ],
    devServer: {
        contentBase: "./dist",
        index: "index.html",
        publicPath: "/",
        host: "localhost",
        port: 9205,
        stats: {
            colors: true
        }
    }
}
```

### Expected Behavior
Run webpack-dev-server and open port.

### Actual Behavior
Return an error

### Error Code
```
PS I:\repositories\web_scratch_file_analyze> npm start

> web_scratch_file_analyze@1.0.0 start
> webpack-dev-server --open --mode development

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- I:\repositories\web_scratch_file_analyze\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (I:\repositories\web_scratch_file_analyze\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'I:\\repositories\\web_scratch_file_analyze\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code 1
npm ERR! path I:\repositories\web_scratch_file_analyze
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c webpack-dev-server --open --mode development

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2021-02-10T13_34_09_141Z-debug.log
```

**Comment by alexander-akait** [comment]
You need to change `webpack-dev-server --open --mode development` to `webpack serve --open --mode development`

**Comment by 368573607** [comment]
> You need to change `webpack-dev-server --open --mode development` to `webpack serve --open --mode development`, don't forget to install `webpack-cli`

Thanks!
