### ISSUE TITLE
Using css-loader's :local or ?modules features breaks hot-reload

### ISSUE THREAD

**Issue by snaptopixel** [webpack/webpack-dev-server#318]
Hot-reloading works great for css and scss in my project but as soon as I start using `:local` or `?modules` it will only do a full reload which is a real bummer :cry: 

```
[HMR] Cannot apply update. Need to do a full reload!
dev-server.js:19 [HMR] Error: Aborted because 105 is not accepted
    at hotApply (http://localhost:8080/bundle.js:356:31)
    at hotUpdateDownloaded (http://localhost:8080/bundle.js:269:13)
    at hotAddUpdateChunk (http://localhost:8080/bundle.js:249:13)
    at webpackHotUpdateCallback (http://localhost:8080/bundle.js:5:12)
    at http://localhost:8080/0.8521540be4e82d3810b2.hot-update.js:1:1
```

**Comment by snaptopixel** [comment]
Note: This issue has also been posted in css-loader here https://github.com/webpack/css-loader/issues/186
