### ISSUE TITLE
HookWebpackError: Cannot read property 'updatedChunkIds' of undefined (again)

### ISSUE THREAD

**Issue by fefrei** [webpack/webpack-dev-server#3233]
This is a re-occurrence of the symptom known from #2960, likely from a different cause. See that issue for some previous discussion.

- Operating System: Windows 10 19042.928
- Node Version: v14.16.1
- NPM Version: 6.14.12
- webpack Version: 5.36.0
- webpack-dev-server Version: 3.11.2
- Browser: _irrelevant, this is a build issue_

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

See here: https://github.com/fefrei/webpack-serve-updatedChunkIds-mwe

### Reproduction Steps

Set up the MWE:

- `git clone https://github.com/fefrei/webpack-serve-updatedChunkIds-mwe.git`
- `cd webpack-serve-updatedChunkIds-mwe/webapp`
- `npm ci`

Now, start Webpack Dev Server by running `npm run start`, and wait for the build to finish.
Open `pseuCoTesting.tsx` and uncomment the indicated line.

The compilation crashes with this error:

```
i ｢wdm｣: Compiling...
× ｢wdm｣: HookWebpackError: Cannot read property 'updatedChunkIds' of undefined
    at makeWebpackError (webapp\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at webapp\node_modules\webpack\lib\Compilation.js:2466:12
    at eval (eval at create (webapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at fn (webapp\node_modules\webpack\lib\Compilation.js:427:17)
    at Hook.eval [as callAsync] (eval at create (webapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (webapp\node_modules\tapable\lib\Hook.js:18:14)
    at cont (webapp\node_modules\webpack\lib\Compilation.js:2463:34)
    at webapp\node_modules\webpack\lib\Compilation.js:2509:10
    at webapp\node_modules\neo-async\async.js:2830:7
    at Object.each (webapp\node_modules\neo-async\async.js:2850:39)
-- inner error --
TypeError: Cannot read property 'updatedChunkIds' of undefined
    at webapp\node_modules\webpack\lib\HotModuleReplacementPlugin.js:656:11
    at exports.forEachRuntime (webapp\node_modules\webpack\lib\util\runtime.js:64:3)
    at webapp\node_modules\webpack\lib\HotModuleReplacementPlugin.js:653:9
    at fn (webapp\node_modules\webpack\lib\Compilation.js:425:10)
    at Hook.eval [as callAsync] (eval at create (webapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (webapp\node_modules\tapable\lib\Hook.js:18:14)
    at cont (webapp\node_modules\webpack\lib\Compilation.js:2463:34)
    at webapp\node_modules\webpack\lib\Compilation.js:2509:10
    at webapp\node_modules\neo-async\async.js:2830:7
    at Object.each (webapp\node_modules\neo-async\async.js:2850:39)
× ｢wdm｣: caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'updatedChunkIds' of undefined
    at webapp\node_modules\webpack\lib\HotModuleReplacementPlugin.js:656:11
    at exports.forEachRuntime (webapp\node_modules\webpack\lib\util\runtime.js:64:3)
    at webapp\node_modules\webpack\lib\HotModuleReplacementPlugin.js:653:9
    at fn (webapp\node_modules\webpack\lib\Compilation.js:425:10)
    at Hook.eval [as callAsync] (eval at create (webapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (webapp\node_modules\tapable\lib\Hook.js:18:14)
    at cont (webapp\node_modules\webpack\lib\Compilation.js:2463:34)
    at webapp\node_modules\webpack\lib\Compilation.js:2509:10
    at webapp\node_modules\neo-async\async.js:2830:7
    at Object.each (webapp\node_modules\neo-async\async.js:2850:39)
```

The inverse (starting with this line commented in, then commenting it out) also crashes like this.

**Comment by alexander-akait** [comment]
@fefrei wierd, I can't reproduce, do you have global install webpack/webpack-cli?

**Comment by fefrei** [comment]
> @fefrei weird, I can't reproduce, do you have global install webpack/webpack-cli?

No, they're installed locally only.

> What is line? I try comment all lines and no problems...

Sorry, maybe I should have been clearer. Look in [`pseuCoTesting.tsx`](https://github.com/fefrei/webpack-serve-updatedChunkIds-mwe/blob/main/webapp/src/interactive/pseuco/pseucoTesting/pseuCoTesting.tsx#L9), it contains this block:

```ts
    // ↓ uncomment this to trigger the bug
    // return <PseuCoDebugger />;
    // ↑ uncomment this to trigger the bug
```

This is what you want to touch – *un*comment the second line from this block (causing `PseuCoDebugger` to be used), this triggers the bug for me.

**Comment by alexander-akait** [comment]
Yep, bug, confirmed, in TODO

**Comment by fefrei** [comment]
Wohoo! Happy to finally have a confirmed repro of this 🎉
Thanks for your work here!

**Comment by sokra** [comment]
While this commit https://github.com/webpack/webpack/commit/1ca93aaa6bda2dedb8b2b6d545ff9d8a6f85d954 already makes the problem disappear in the repro, webpack/webpack#13449 fixes the real bug behind it.

**Comment by fefrei** [comment]
Thank you for your work on this! ❤️
