### ISSUE TITLE
Cant run dev server

### ISSUE THREAD

**Issue by xvilo** [webpack/webpack-dev-server#346]
Hello,

I managed to run it one time, but I made a mistake in the config files. Edited them but now i cant open the dev server anymore... I also removed everything and created a new clone of the git repositry... 

What i'm getting is:
```

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'devserver' ]
2 info using npm@2.13.1
3 info using node@v0.12.7
4 verbose run-script [ 'predevserver', 'devserver', 'postdevserver' ]
5 info predevserver wordpress-hybrid-client@2.0.0-alpha2
6 info devserver wordpress-hybrid-client@2.0.0-alpha2
7 verbose unsafe-perm in lifecycle true
8 info wordpress-hybrid-client@2.0.0-alpha2 Failed to exec devserver script
9 verbose stack Error: wordpress-hybrid-client@2.0.0-alpha2 devserver: `webpack-dev-server --port 8080 --json --progress`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid wordpress-hybrid-client@2.0.0-alpha2
11 verbose cwd /Volumes/ZEUS/Users/xvilo/projects/regio25app/config
12 error Darwin 15.2.0
13 error argv "node" "/usr/local/bin/npm" "run" "devserver"
14 error node v0.12.7
15 error npm  v2.13.1
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error wordpress-hybrid-client@2.0.0-alpha2 devserver: `webpack-dev-server --port 8080 --json --progress`
20 error spawn ENOENT
21 error Failed at the wordpress-hybrid-client@2.0.0-alpha2 devserver script 'webpack-dev-server --port 8080 --json --progress'.
21 error This is most likely a problem with the wordpress-hybrid-client package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     webpack-dev-server --port 8080 --json --progress
21 error You can get their info via:
21 error     npm owner ls wordpress-hybrid-client
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

I am using the newest version of Mac OSX

**Comment by SpaceK33z** [comment]
Do you still have this issue?

**Comment by SpaceK33z** [comment]
I'm closing this issue because of inactivity. Feel free to comment, and we can always re-open it again.

**Comment by muhammadfaizan** [comment]
having same issue
