### ISSUE TITLE
No module factory

### ISSUE THREAD

**Issue by Chaoste** [webpack/webpack-dev-server#353]
Hey guys,
I'm working on Windows 10 on a big project (so excuse the big config file below). A few weeks ago I installed webpack and webpack-dev-server. It uses the angular-, uglify- and hmr-plugin. Since two weeks webpack-dev-server throws following error:

```
C:\Users\Thomas\Dokumente\Uni\UCSMA-Uber\test\demo2\n2o>webpack-dev-server
http://localhost:8080/webpack-dev-server/
webpack result is served from /app/
content is served from C:\Users\Thomas\Dokumente\Uni\UCSMA-Uber\test\demo2\n2o
C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack-dev-middleware\middleware.js:104
                        if(err) throw err;
                                ^

Error: No module factory available for dependency type: ModuleDependency
    at Compilation.addModuleDependencies (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:181:20)
    at Compilation.processModuleDependencies (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:170:7)
    at Compilation.moduleReady (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:412:9)
    at Compilation.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:408:16)
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:123:4
    at Array.forEach (native)
    at callback (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:122:12)
    at Compilation.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (C:\Users\Thomas\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
```

I'm using the newest version for NodeJS (32bit, because node-gyp fails on 64bit - don't know why), webpack and webpack-dev-server. I have one config file which has two modi (normal or dev-server).
This might be a problem of webpack-dev-server because executing webpack ("..\node_modules\.bin\webpack.cmd") **doesn't** throw an error. The error also disappears **removing all three plugins**.
I also tried switching to webpack-dev-server@1.13 / 1.12 / 1.11 and webpack@1.12.1 (due to this issue: [webpack#1713](https://github.com/webpack/webpack/issues/1713))

    var path = require('path');
    var AngularPlugin = require('angular-webpack-plugin');
    var webpack = require("webpack");
    require("css-selector-tokenizer");
    var merge = require('webpack-merge');
    var devServer = (process.env.npm_lifecycle_event === 'start-dev-server') || (process.argv.indexOf('start-dev-server') >= 0) || (process.argv.indexOf('webpack-dev-server') >= 0);
    
    common = {
        entry: 'n2o',
        output: {
            path: 'public/app',
            filename: 'n2o.min.js',
            publicPath: 'app/'
        },
      	externals: {
        		"jquery": "jQuery"
      	},
        resolve: {
            root: [
                // Directories containing modules
                path.resolve('public'),
    	          path.resolve('public', 'assets/libs'),
                path.resolve('public', 'components'),
                path.resolve('public', 'components/settings'),
                path.resolve('public', 'components/splitapp'),
                path.resolve('public', 'components/register'),
                path.resolve('public', 'shared/postContent'),
                path.resolve('public', 'shared'),
                // Needed for webpack-dev-server modules
                path.resolve('public', '../../node_modules')
            ],
    	      modulesDirectories:['public/assets/libs'],
    	      'dev-tool':'eval',
            alias: {
                // Replace module names with belonging file names
                n2o$: 'app.module',
                ngFileUpload$: 'ng-file-upload',
                toaster$: 'angularjs-toaster',
                ngCookies$: 'angular-cookies',
    	          'ui.router$': __dirname+'/public/assets/libs/angular-ui-router/release/angular-ui-router.js',
    	          'jQuery$': __dirname+'/public/assets/libs/jquery/dist/jquery.js',
                registration$: 'register',
                ngAnimate$: 'angular-animate',
                'mm.foundation$': __dirname+'/public/assets/libs/angular-foundation/mm-foundation.js',
                vcRecaptcha$:'angular-recaptcha',
                filters$: 'postContentController',
                'cfp.hotkeys$':'angular-hotkeys',
                'angulartics.google.analytics$':__dirname+'/public/assets/libs/angulartics/dist/angulartics-ga.min.js',
                splitapp$:'splitappController',
                register$:'registerController',
                'ngTouch$':'angular-touch',
                'ui-rangeSlider$':__dirname+'/public/assets/libs/angular-rangeslider/angular.rangeSlider.js',
                ngSanitize:'angular-sanitize',
                settingsModule: 'settingsMasterController',
                ngTagsInput$:'ng-tags-input',
                'chart.js$':'angular-chart.js',
                // Webpack-dev-server dependency
                'inherits':__dirname+'\\..\\node_modules\\inherits',
                n2o: path.resolve('public'),
                ngRoute$: 'angular-route'
            }
        },
        module:  {
            loaders: [{
    	        // Copy png, jpg, jpeg, gif, svg, woff, woff2, ttf, eot files to output
    	        // Rename the file using the asset hash
    	        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)/,
    	        loader: 'file'
            }, {
    	        // Allow loading html through js
    	        test: /\.html$/,
    	        loader: 'raw'
            }, {
              test: /\.css$/,
              loader: "style-loader!css-loader"
            },
            {
              test: /\.json$/,
              loader: "json-loader"
            }]
        },
        plugins: [
          // Make angular variable available, take angular.module() as requires and
          // resolve modules using angular conventions.
    	    new AngularPlugin()
        ]
    };
    
    // For using the development mode the webpack-dev-server has to run with
    // following config.
    if(devServer) {
      common.output.publicPath = 'http://localhost:9090/app/'
      module.exports = merge(common, {
        devtool: 'eval-source-map',
        debug: true,
        devServer: {
          historyApiFallback: true,
          hot: true,
          inline: true,
          quiet: true,
          host: process.env.HOST,
          port: '9090'
        },
        plugins: [
          new webpack.HotModuleReplacementPlugin()
        ]
      })
    } else {
      module.exports = merge(common, {
        plugins: [
          new webpack.optimize.UglifyJsPlugin({
            minimize: true,
            sourceMap: false,
            mangle: false,
            compress: {
              warnings: false
            }
          })
        ]
      })
    }

I would appreciate your help :)
Thomas

**Comment by SpaceK33z** [comment]
Do you still have this problem? If so, a repo were you have reduced the problem as far as possible would be handy. This config file is way too big to start.

**Comment by SpaceK33z** [comment]
I'm closing this issue because of inactivity. Feel free to comment, and we can always re-open it again.
