### ISSUE TITLE
Bug: webpack-dev-server 4.0.0 throws an error when I try "webpack serve"  

### ISSUE THREAD

**Issue by AguacateContreras** [webpack/webpack-dev-server#3700]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code: webpack.config.js

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
    mode: 'development',
    entry: './src/app.js',
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'bundle.js'
    },
    plugins: [new HtmlWebpackPlugin({
        template: './src/index.html'
    })],
}
```

#### webpack-cli info
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 7.52 GB / 15.61 GB
  Binaries:
    Node: 10.24.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.20.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 78.12.0esr
  Packages:
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    webpack: ^5.51.1 => 5.51.1 
    webpack-cli: ^4.8.0 => 4.8.0 
    webpack-dev-server: ^4.0.0 => 4.0.0 
  Global Packages:
    webpack-cli: 4.7.2
    webpack: 5.50.0
```
#### webpack-cli version
```
webpack 5.51.1
webpack-cli 4.8.0
webpack-dev-server 4.0.0
```
### Action
I ran:
```
$ webpack serve
```
### Expected Behavior
webpack server starts and everything works fine.

### Actual Behavior
webpack throws an error: (I replaced the absolute path with "...")
```js
 static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (.../node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (.../node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (.../node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Server.getWebSocketServerImplementation (.../node_modules/webpack-dev-server/lib/Server.js:1195:28)
```

### For Bugs; How can we reproduce the behavior?
Use webpack-dev-server version 4.0.0
This error does not happens in the version: 3.11.2

**Comment by 0es** [comment]
webpack-dev-server@4 required node version >= **12.13.0**

**Comment by snitin315** [comment]
Yes, @AguacateContreras your node version is `10.24.0`, please upgrade to node v12+ and it will work fine.

**Comment by AguacateContreras** [comment]
Thank you guys!
