### ISSUE TITLE
throw error when using webpack.DefinePlugin

### ISSUE THREAD

**Issue by djyde** [webpack/webpack-dev-server#388]
Error message:

```bash
/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^

TypeError: Cannot read property 'name' of undefined
    at Compilation.addModuleDependencies (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:180:108)
    at Compilation.processModuleDependencies (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:170:7)
    at Compilation.<anonymous> (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:319:11)
    at /Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/randy/.nvm/versions/node/v4.2.1/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
```

config:

```javascript
var definePlugin = new webpack.DefinePlugin({
  __DEV__: true
})

config.plugins = [definePlugin]
```

Throw error when I use `__DEV__` in script files. But using `$ webpack --config myconfig.js` is work.

**Comment by sokra** [comment]
propably the dependencies missmatch. webpack and webpack-dev-server installed locally?

**Comment by SpaceK33z** [comment]
@djyde, did you manage to fix it? I just checked, and can't reproduce it. It is very likely a config issue.
