### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by januwA** [webpack/webpack-dev-server#3903]
### Actual Behavior

```sh
$ npm start 

> ajanuw-react-rxservice@1.2.0 start /root/react-rxservice
> cross-env TS_NODE_PROJECT=config/webpack/tsconfig.json NODE_ENV=development ts-node config/webpack/dev-server.ts

(node:1198) UnhandledPromiseRejectionWarning: /root/react-rxservice/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/root/react-rxservice/node_modules/webpack-dev-server/lib/Server.js:1009:28)
    at Server.createWebSocketServer (/root/react-rxservice/node_modules/webpack-dev-server/lib/Server.js:1589:38)
    at Server.start (/root/react-rxservice/node_modules/webpack-dev-server/lib/Server.js:2147:12)
(node:1198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
$ npx webpack-cli info

  System:
    OS: Linux 5.10 CentOS Linux 8
    CPU: (2) x64 Intel(R) Celeron(R) CPU G1840 @ 2.80GHz
    Memory: 4.27 GB / 6.12 GB
  Binaries:
    Node: 10.24.0 - /usr/bin/node
    Yarn: 1.22.11 - /mnt/c/Users/Administrator/AppData/Roaming/npm/yarn
    npm: 6.14.11 - /usr/bin/npm
  Packages:
    clean-webpack-plugin: ^4.0.0 => 4.0.0 
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    webpack: ^5.55.1 => 5.55.1 
    webpack-cli: ^4.8.0 => 4.8.0 
    webpack-dev-server: ^4.3.0 => 4.3.0 
    webpack-merge: ^5.8.0 => 5.8.0 
```

**Comment by ylemkimon** [comment]
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
> Minimum supported `Node.js` version is `12.13.0`.

**Comment by snitin315** [comment]
The answer is above, please use `node version >= 12.13.0`.
