### ISSUE TITLE
Failing to start server on El Capitan

### ISSUE THREAD

**Issue by favetelinguis** [webpack/webpack-dev-server#409]
Getting the following error when trying to launch:
Are there any issues with the versions I'm using?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle animation@1.0.0~prestart: animation@1.0.0
6 silly lifecycle animation@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle animation@1.0.0~start: animation@1.0.0
8 verbose lifecycle animation@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle animation@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/henke/Downloads/9781484212615/chapter 4/animation/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle animation@1.0.0~start: CWD: /Users/henke/Downloads/9781484212615/chapter 4/animation
11 silly lifecycle animation@1.0.0~start: Args: [ '-c', 'webpack-dev-server --progress' ]
12 silly lifecycle animation@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle animation@1.0.0~start: Failed to exec start script
14 verbose stack Error: animation@1.0.0 start: `webpack-dev-server --progress`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid animation@1.0.0
16 verbose cwd /Users/henke/Downloads/9781484212615/chapter 4/animation
17 error Darwin 15.3.0
18 error argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error animation@1.0.0 start: `webpack-dev-server --progress`
22 error Exit status 1
23 error Failed at the animation@1.0.0 start script 'webpack-dev-server --progress'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the animation package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --progress
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs animation
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls animation
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by favetelinguis** [comment]
Just updated npm to v3.7.3 but still getting the same problem.

**Comment by favetelinguis** [comment]
turned out node was already using 8080.
