### ISSUE TITLE
Module build failed with webpack-dev-server

### ISSUE THREAD

**Issue by fancy-mind** [webpack/webpack-dev-server#413]
The following is the error message 

ERROR in ./public/main.js
Module build failed: SyntaxError: E:/Coding/Workspaces/node/helloworld/public/main.js: Unexpected token (6:2)
  4 |
  5 | ReactDOM.render(
> 6 |   <CommentBox url="http://localhost:8080/api/comments"/>,
    |   ^
  7 |   document.getElementById('content')
  8 | );
  9 |
    at Parser.pp.raise (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:1425:13)
    at Parser.pp.unexpected (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:2905:8)
    at Parser.pp.parseExprAtom (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:754:12)
    at Parser.pp.parseExprSubscripts (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:509:19)
    at Parser.pp.parseMaybeUnary (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:489:19)
    at Parser.pp.parseExprOps (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:420:19)
    at Parser.pp.parseMaybeConditional (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:402:19)
    at Parser.pp.parseMaybeAssign (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:365:19)
    at Parser.pp.parseExprListItem (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:1232:16)
    at Parser.pp.parseCallExpressionArguments (E:\Coding\Workspaces\node\helloworld\node_modules\babel-core\node_modules\babylon\index.js:585:20)
 @ multi app

---------------------------

And this is my webpack.config   

var path = require('path');
var webpack = require('webpack');
module.exports = {
  entry: {
    app: [
          'webpack-dev-server/client?http://127.0.0.1:3000', // WebpackDevServer host and port
          'webpack/hot/only-dev-server',
          './public/main.js'
         ]
    },
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js',
    publicPath: 'http://127.0.0.1:3000/static/'
  },
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['react-hot-loader','babel-loader'] ,include: path.join(__dirname,'public')},
      { test: /\.less$/, loader: 'style-loader!css-loader!less-loader' }, 
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' } 
    ]
  },
  plugins:[
    new webpack.HotModuleReplacementPlugin()
  ]
};

**Comment by sokra** [comment]
Closing because this is not related to webpack-dev-server, but to webpack instead.

> Note: I'm cleaning up the issues list. For questions please use [stackoverflow](http://stackoverflow.com/tags/webpack), or for issues file them on the [webpack](https://github.com/webpack/webpack) repository
