### ISSUE TITLE
Webpack dev server API compiling on saves but no HMR in browser

### ISSUE THREAD

**Issue by romane-echino** [webpack/webpack-dev-server#4314]
Hi, I have some issues with webpack-dev-server@4.7.4 & webpack 5.69.1 over react with typescript

### context
I have a component SDK that provide build & run features for some projects. I used an old version of webpack and devserver for 1 year but I needed to work with some polyfills and for that needed to update to webpack >= 5.

Basically I build every files needed in a /build directory and run wepack-dev-server.

Everthing works perfectly but the hot reload. Everytime I make a change I see some output in the console 

```powershell
asset bundle.js 320 KiB [emitted] (name: main)
asset main.08c6253af208fbdf337d.hot-update.js 6.14 KiB [emitted] [immutable] [hmr] (name: main)
asset main.08c6253af208fbdf337d.hot-update.json 28 bytes [emitted] [immutable] [hmr]
Entrypoint main 327 KiB = bundle.js 320 KiB main.08c6253af208fbdf337d.hot-update.js 6.14 KiB
cached modules 216 KiB [cached] 31 modules
runtime modules 27 KiB 12 modules
./src/components/SomeTest/SomeTest.tsx 4.04 KiB [built] [code generated]
webpack 5.69.1 compiled successfully in 129 ms
```

The only thing that bothers me is that Chrome (the browser) doesn't reload it self. Secondly, when I try to reload manually or force-reload (CTRL+R) my changes aren't reloaded.

Finally I remember back then that there was in the browsers console something about [WDS] Hot reload... that doesn't appear anymore.

Here is my webpack config

```javascript
"use strict";
/**
 * generates:
 *  - build/bundle.js
 *
 */
var webpack = require("webpack");
var path = require('path');
process.env.NODE_ENV = 'development';
module.exports = {
    mode: 'development',
    target: 'web',
    plugins: [
        new webpack.EnvironmentPlugin({
            "process.env.NODE_ENV": process.env.NODE_ENV
        })
    ],
    entry: path.resolve('src/index.ts'),
    output: {
        libraryTarget: "commonjs",
        filename: "bundle.js",
        path: path.resolve('build/static')
    },
    externals: [
        {
            react: 'react',
            'react-router': 'react-router'
        },
        /^@echino\/echino\.ui\..*/
    ],
    module: {
        rules: [
            {
                test: /\.[tj]sx?$/,
                exclude: path.resolve(__dirname, "node_modules"),
                use: {
                    loader: "babel-loader",
                }
            },
            {
                test: /\.s[ac]ss$/i,
                use: [
                    // Creates `style` nodes from JS strings
                    'style-loader',
                    // Translates CSS into CommonJS
                    'css-loader',
                    // Compiles Sass to CSS
                    'sass-loader',
                ],
            },
            {
                test: /\.svg/,
                type: 'asset/inline'
            },
        ]
    },
    devServer: {
        static: {
            directory: path.join(process.cwd(), 'build')
        },
        hot: true,
        port: 9000,
    },
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
    }
};
```
And the code that launches the server

```javascript
const compiler = Webpack(webpackConfig);
const devServerOptions = { ...webpackConfig.devServer, open: true };
const server = new WebpackDevServer(devServerOptions, compiler);

const runServer = async () => {
    console.log('Starting server...');
    await server.start();
};

runServer();
```

.babelrc

```json
{
	"presets": [
		"@babel/preset-env",
		"@babel/preset-typescript",
		"@babel/preset-react"
	],
	"plugins": [
		"@babel/proposal-class-properties",
		"@babel/proposal-object-rest-spread"
	]
}
```

I tried so many thing and saw so many answers on the web but the thing is there is a great amount of version and it's quite difficult to know which configuration is right for the last version.

Thanks in advance!

**Comment by romane-echino** [comment]
I also tried what the documentation stated with HMR and devServer API

```javascript
plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
        template: path.resolve('build/index.html'),
        filename: 'index.html'
    }),
],
entry: [
    // Runtime code for hot module replacement
    'webpack/hot/dev-server.js',
    // Dev server client for web socket transport, hot and live reload logic
    'webpack-dev-server/client/index.js?hot=true&live-reload=true',
    path.resolve('src/index.ts')
],
```

And now the hot reload seems to work but totally breaks react

```console
[HMR] Waiting for update signal from WDS...
[webpack-dev-server] Hot Module Replacement enabled.
[webpack-dev-server] Live Reloading enabled.

bundle.js:365 Uncaught ReferenceError: require is not defined
    at Object.react (bundle.js:365:1)
    at __webpack_require__ (bundle.js:394:33)
    at fn (bundle.js:593:21)
    at eval (SampleComponent.tsx:5:63)
    at Module../src/components/SampleComponent/SampleComponent.tsx (bundle.js:277:1)
    at __webpack_require__ (bundle.js:394:33)
    at fn (bundle.js:593:21)
    at eval (index.ts:6:101)
    at Module../src/index.ts (bundle.js:299:1)
    at __webpack_require__ (bundle.js:394:33)
````

**Comment by romane-echino** [comment]
Ok I talked to my PM and I can't publish the same project for NDA purpose. So it took a little bit of time and I managed to make the smallest project with the same architecture.

https://github.com/romane-echino/test-comp

Everthing that happens during build and run happens in /scripts

**Comment by romane-echino** [comment]
Hi Alexander I found the problem! The thing is webpack 4 used to compile the bundle.js where you specified the publicPath in dev server. It's not the case anymore apparently. You have to specify the following :

```javascript
output: {
    libraryTarget: "commonjs",
    filename: "bundle.js",
    path: path.resolve('build/static'),
    publicPath: '/static' // <-------
  },
```

So with this the bundle.js is served under the correct publicPath during compilation. HMR now works perfectly, sorry for the inconvenience you can now close this issue.

Cheers from switzerland!

**Comment by alexander-akait** [comment]
@romane-echino nice to hear, sorry for delay, there are some problems with internet due situation in the world, feel free to feedback/ping
