### ISSUE TITLE
I am migrating my webpack v4 to v5 i'm facing the below issue

### ISSUE THREAD

**Issue by hariseshathri** [webpack/webpack-dev-server#4393]
[webpack-cli] D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\servers\WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Server.getServerTransport (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:1663:28)
    at Server.createWebSocketServer (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:2443:57)
    at Server.start (D:\22.05\FORMS-1065\core-ui-application\node_modules\webpack-dev-server\lib\Server.js:3229:12)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)``

**Comment by alexander-akait** [comment]
How you run dev server? Maybe you can provide repo?

**Comment by progerchai** [comment]
```javascript 
webpack server --mode=development --color --config=./script/webpack.dev.js
```
Sorry, My project is quite complex and create the repo is a bit difficult for me  T-T

**Comment by alexander-akait** [comment]
Can you update Node.js? 12 is EOL

**Comment by progerchai** [comment]
Yes, update node to 16.13.0 worked too

**Comment by alexander-akait** [comment]
Good
