### ISSUE TITLE
Bump memfs to 3.4.2

### ISSUE THREAD

**Issue by ivanbacher** [webpack/webpack-dev-server#4440]
### Bug report
installed node v18.2.0

Dev server randomly dies with the following error message:

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (/Users/.../node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (/Users/.../node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (/Users/.../node_modules/memfs/lib/volume.js:1962:22)
    at class_1.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)

Node.js v18.2.0
```

Found [this issue](https://github.com/streamich/memfs/issues/828) on `memfs` library:

> 🎉 This issue has been resolved in version 3.4.2 🎉

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-dev-middleware/issues/1268, because it is used in `webpack-dev-middleware`

**Comment by ivanbacher** [comment]
Sorry, this is actually an issue with `webpack-dev-middleware`. Also created a [bug report on that repo](https://github.com/webpack/webpack-dev-middleware/issues/1268#issue-1239099731). Once `memfs` gets updated there, will probably need to bump  `webpack-dev-middleware` to newest version.

**Comment by alexander-akait** [comment]
When we done release `webpack-dev-middleware` you can update own deps, I don't think we need to do release for each patch here
