### ISSUE TITLE
Cannot run webpack-dev-server --content-base src --inline --hot

### ISSUE THREAD

**Issue by aw3s0me** [webpack/webpack-dev-server#452]
When try to run command. it gives me such error in log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev react-tutorials@0.0.0
6 info dev react-tutorials@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-tutorials@0.0.0 Failed to exec dev script
9 verbose stack Error: react-tutorials@0.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-tutorials@0.0.0
11 verbose cwd C:\work\react-tuts\react-js-tutorials\2-react-router
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error react-tutorials@0.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
17 error Exit status 1
18 error Failed at the react-tutorials@0.0.0 dev script 'webpack-dev-server --content-base src --inline --hot'.
18 error This is most likely a problem with the react-tutorials package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --content-base src --inline --hot
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-tutorials
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-tutorials
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by SpaceK33z** [comment]
Do you still have this issue? For most Windows users it works fine.

**Comment by SpaceK33z** [comment]
I'm closing this issue because of inactivity. Feel free to comment, and we can always re-open it again.

**Comment by ortallevi07** [comment]
I have this issue on Linux.
