### ISSUE TITLE
Getting the error "SyntaxError: Invalid or unexpected token" at webpack-dev-server/lib/getPort.js:13  

### ISSUE THREAD

**Issue by Saamin-Rahman** [webpack/webpack-dev-server#4526]
### Actual Behavior

I am using webpack-dev-server to bundle sass and javascript in a glitch node project(glitch.com)
When I run npm start I found the following log:
```
> material-bundling-kit@1.0.0 start /app
> webpack serve

[webpack-cli] /rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/getPort.js:13
const maxPort = 65_535;
                ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Function.getFreePort (/rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/Server.js:397:21)
    at Server.start (/rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/Server.js:3200:40)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:54:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! material-bundling-kit@1.0.0 start: `webpack serve`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the material-bundling-kit@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/12.0.0/_logs/2022-07-21T11_52_43_948Z-debug.log
```
![Screenshot 2022-07-21 182035](https://user-images.githubusercontent.com/108727798/180212624-85aaddba-3207-4681-91d2-0247d718e373.png)

### Expected Behavior 

When I open "https://responsible-swanky-opportunity.glitch.me/" I should see the following 
![Result Image](https://github.com/material-components/material-components-web/blob/master/docs/hello_world.png?raw=true)
### How Do We Reproduce?

Please remix the project in glitch "https://glitch.com/~responsible-swanky-opportunity"

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
> material-bundling-kit@1.0.0 start /app
> webpack serve

[webpack-cli] /rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/getPort.js:13
const maxPort = 65_535;
                ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Function.getFreePort (/rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/Server.js:397:21)
    at Server.start (/rbd/pnpm-volume/09b5e1e5-6472-40e7-968b-c163065cb415/node_modules/webpack-dev-server/lib/Server.js:3200:40)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:54:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:828:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! material-bundling-kit@1.0.0 start: `webpack serve`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the material-bundling-kit@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npm-cache/12.0.0/_logs/2022-07-21T11_52_43_948Z-debug.log
```

**Comment by alexander-akait** [comment]
Please update `Node.js` version, you have an old version
