### ISSUE TITLE
Debug breaks on current release candidate

### ISSUE THREAD

**Issue by CrashyBang** [webpack/webpack-dev-server#718]
Using: `v2.2.0-rc.0`

**Do you want to request a *feature* or report a *bug*?**

Was originally a bug posted [here](http://stackoverflow.com/questions/41218364/babel-preset-env-not-working-with-webpack-dev-server-v2-2-0-rc-0/41234462) but is relevant to all `rc` users.

**If the current behavior is a bug, please provide the steps to reproduce.**

There is currently an [issue](https://github.com/visionmedia/debug/issues/381) with the `debug` module which has been fixed on master but not officially released yet.

It prevents the sever from running correctly with the following output:

```
ERROR in ./~/debug/browser.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/otis/Developer/hassle/node_modules/debug"                                                        
    at /home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19                                                                     
    at Array.map (native)                                                                                                                                                               
    at OptionManager.resolvePresets (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)                                      
    at OptionManager.mergePresets (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)                                        
    at OptionManager.mergeOptions (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)                                        
    at OptionManager.init (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)                                                
    at File.initOptions (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/index.js:216:65)                                                                   
    at new File (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/file/index.js:139:24)                                                                           
    at Pipeline.transform (/home/otis/Developer/hassle/node_modules/babel-core/lib/transformation/pipeline.js:46:16)                                                                    
    at transpile (/home/otis/Developer/hassle/node_modules/babel-loader/lib/index.js:38:20)                                                                                             
 @ ./~/sockjs-client/lib/main.js 25:10-26                                                                                                                                               
 @ ./~/sockjs-client/lib/entry.js                                                                                                                                                       
 @ (webpack)-dev-server/client/socket.js                                                                                                                                                
 @ (webpack)-dev-server/client?http://localhost:4000                                                                                                                                    
 @ multi main
```

To fix in the meantime you can add this to your `package.json`:
```json
"debug": "git://github.com/visionmedia/debug#master"
```

**What is the expected behavior?**

For the server to run without breaking.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

Using webpack `v2.2.0-rc.0` and Ubuntu 16.04.

**Comment by SpaceK33z** [comment]
What exactly do you suggest I can do with that here? `debug` is not a direct dependency of webpack-dev-server...

**Comment by CrashyBang** [comment]
Hey @SpaceK33z I put it here as an intended reference for other users using `v2.2.0-rc.0` who come across the problem wand provided a `_in the meantime_ fix. I do not expect you to do anything with it, just thought you may be interested in knowing...?

**Comment by SpaceK33z** [comment]
Sure, thanks for sharing, but this is really a configuration issue. You shouldn't let babel-loader search in all `node_modules/` packages, if you do that any random package can cause breakage.

Either use babel-loader with an `exclude` or `include` property like this:

```js
{
    test: /\.js$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
},
```

**Comment by CrashyBang** [comment]
Hey @SpaceK33z I have that already, from what I can tell from the linked issue it has nothing to do with my babel config, it is also worth noting it works flawlessly when doing a build without the `webpack-dev-server` so I do not think doing the above will help.

**Comment by SpaceK33z** [comment]
I really doubt that, webpack-dev-server doesn't even "know" about Babel, it doesn't have it as dependency nor does it do anything with Babel. In your StackOverflow question I saw you doing `exclude: ['/node_modules/']`, I think that should be `exclude: [/node_modules/]`.

**Comment by CrashyBang** [comment]
I will double check tonight when I get home but all of my other excludes have been handled like that and appear to be working, will let you know.

**Comment by CrashyBang** [comment]
Hey @SpaceK33z only just got back to this today, looks like you were spot on about the `/node_modules/` I have updated and everything appears to be working.

Cheers.
