### ISSUE TITLE
proxying websockets broken in 2.2.1

### ISSUE THREAD

**Issue by tonygentilcore** [webpack/webpack-dev-server#769]
### Expected behavior
Able to proxy websockets with webpack 2.

### Actual behavior
Not able to proxy websockets with webpack 2.

### Setup
webpack-dev-server v2.2.1 was just pushed to stable.

At the previous stable version, v1.16.2, this webpack config works:
```js
  devServer: {
    https: true,
    proxy: {
      '/my-backend': {
        changeOrigin: true,
        pathRewrite: {'^/my-backend': ''},
        target: myBackendUrl,
        ws: true,
      },
  }
```

At v2.2.1, it does not. Instead I get:
```
TypeError: Cannot read property 'on' of null
    at catchUpgradeRequest (/work/my-project/node_modules/http-proxy-middleware/lib/index.js:56:19)
    at middleware (/work/my-project/node_modules/http-proxy-middleware/lib/index.js:48:13)
    at /work/my-project/node_modules/webpack-dev-server/lib/Server.js:223:15
    at Layer.handle [as handle_request] (/work/my-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/work/my-project/node_modules/express/lib/router/index.js:312:13)
    at /work/my-project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/work/my-project/node_modules/express/lib/router/index.js:330:12)
    at next (/work/my-project/node_modules/express/lib/router/index.js:271:10)
    at middleware (/work/my-project/node_modules/http-proxy-middleware/lib/index.js:43:13)
    at /work/my-project/node_modules/webpack-dev-server/lib/Server.js:223:15
    at Layer.handle [as handle_request] (/work/my-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/work/my-project/node_modules/express/lib/router/index.js:312:13)
    at /work/my-project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/work/my-project/node_modules/express/lib/router/index.js:330:12)
    at next (/work/my-project/node_modules/express/lib/router/index.js:271:10)
    at goNext (/work/my-project/node_modules/webpack-dev-middleware/middleware.js:28:49)
```

**Comment by SpaceK33z** [comment]
Interesting, that looks like an error in `http-proxy-middleware` package. That package was also used in v1.16.x, but you perhaps had an older version that didn't contain this bug.

I see that you also created an issue over there, https://github.com/chimurai/http-proxy-middleware/issues/143.

**Comment by tonygentilcore** [comment]
It's strange. I filed in both places because webpack-dev-server v1.16.x and v2.2.x both depend on http-proxy-middleware v0.17.x. That suggests the usage changed somehow.

**Comment by ohjames** [comment]
With angular-cli I don't see any error from webpack-dev-server but the proxied websocket connections are unusable.

**Comment by kjda** [comment]
having the same issue, happens when https is enabled

**Comment by cdupetit** [comment]
You must set `secure: false` in the ws proxy definition: 
```
'/ws': {
    target: 'ws://wss_host:wss_port',
    ws: true,
    secure: false
}
```

**Comment by shellscape** [comment]
Closing due to age, inactivity, and that we're replacing SockJS with a native solution for v3.
