### ISSUE TITLE
webpack-dev-server doesnt start.

### ISSUE THREAD

**Issue by srseven** [webpack/webpack-dev-server#853]
when i issue `npm start` command inside my project directory it doesn't start throws error however `npm build` runs without a issue. The error log file states: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.4.1
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle es6@1.0.0~prestart: es6@1.0.0
6 silly lifecycle es6@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle es6@1.0.0~start: es6@1.0.0
8 verbose lifecycle es6@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle es6@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/srseven/Documents/es6/node_modules/.bin:/u01/app/oracle/product/11.2.0/xe/bin:/u01/app/oracle/product/11.2.0/xe/bin:/home/srseven/.local/share/umake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle es6@1.0.0~start: CWD: /home/srseven/Documents/es6
11 silly lifecycle es6@1.0.0~start: Args: [ '-c', 'webpack-dev-server' ]
12 silly lifecycle es6@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle es6@1.0.0~start: Failed to exec start script
14 verbose stack Error: es6@1.0.0 start: `webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid es6@1.0.0
16 verbose cwd /home/srseven/Documents/es6
17 verbose Linux 4.4.0-66-generic
18 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 verbose node v6.10.0
20 verbose npm  v4.4.1
```
`npm start` output : 

```
> es6@1.0.0 start /home/srseven/Documents/es6
> webpack-dev-server

/home/srseven/Documents/es6/node_modules/webpack-dev-server/bin/webpack-dev-server.js:365
                throw e;
                ^

Error: `output.path` needs to be an absolute path or `/`.
    at Object.setFs (/home/srseven/Documents/es6/node_modules/webpack-dev-middleware/lib/Shared.js:88:11)
    at Shared (/home/srseven/Documents/es6/node_modules/webpack-dev-middleware/lib/Shared.js:214:8)
    at module.exports (/home/srseven/Documents/es6/node_modules/webpack-dev-middleware/middleware.js:22:15)
    at new Server (/home/srseven/Documents/es6/node_modules/webpack-dev-server/lib/Server.js:56:20)
    at startDevServer (/home/srseven/Documents/es6/node_modules/webpack-dev-server/bin/webpack-dev-server.js:358:12)
    at processOptions (/home/srseven/Documents/es6/node_modules/webpack-dev-server/bin/webpack-dev-server.js:322:3)
    at Object.<anonymous> (/home/srseven/Documents/es6/node_modules/webpack-dev-server/bin/webpack-dev-server.js:430:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es6@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the es6 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs es6
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls es6
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/srseven/.npm/_logs/2017-03-19T12_08_32_586Z-debug.log
```

OS : Ubuntu 14.04 
Kernel : 4.4.0-66
Webpack : 2.2.1

**Comment by SpaceK33z** [comment]
Have you read the error? webpack-dev-server can't work with a `output.path` that doesn't start with a `/`, as it says.

**Comment by SpaceK33z** [comment]
I'm going to close this since this is a usage question, please ask on StackOverflow if you need more info.
