### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by daryn-k** [webpack/webpack-dev-server#957]
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:389
                throw e;
                ^

Error: `output.path` needs to be an absolute path or `/`.
    at Object.setFs (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack-dev-middleware\lib\Shared.js:98:11)
    at Shared (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack-dev-middleware\lib\Shared.js:224:8)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack-dev-middleware\middleware.js:22:15)
    at new Server (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\lib\Server.js:68:20)
    at startDevServer (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:382:12)
    at processOptions (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:346:3)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:471:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by daryn-k** [comment]
I hate you all! I can't launch it! What a stupid project, if I can't install it and laucnch it simply!

**Comment by daryn-k** [comment]
It's most stupid thing I ever met!

**Comment by shellscape** [comment]
Welp.
