### ISSUE TITLE
TypeError: flatten.depth is not a function

### ISSUE THREAD

**Issue by limi58** [webpack/webpack-dev-server#989]
run webpack-dev-server is ok, but a few minutes later error happen:

```
D:\web\imbgf\node_modules\bonjour\lib\mdns-server.js:54
      ? flatten.depth(Object.keys(self.registry).map(self._recordsFor.bind(self,
 name)), 1)
                ^

TypeError: flatten.depth is not a function
    at D:\web\imbgf\node_modules\bonjour\lib\mdns-server.js:54:17
    at Array.forEach (native)
    at Server._respondToQuery (D:\web\imbgf\node_modules\bonjour\lib\mdns-server
.js:48:19)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at Socket.<anonymous> (D:\web\imbgf\node_modules\multicast-dns\index.js:45:4
0)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imbgf@0.5.1 dev: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imbgf@0.5.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

windows10
webpack v3.2.0
webpack-dev-server v2.5.1
node 8.0.0
npm 5.1.0

v2.4.5 works fine

**Comment by fnll** [comment]
have same issue for mac
```
/usr/local/lib/node_modules/webpack-dev-server/node_modules/bonjour/lib/mdns-server.js:54
      ? flatten.depth(Object.keys(self.registry).map(self._recordsFor.bind(self, name)), 1)
                ^

TypeError: flatten.depth is not a function
    at /usr/local/lib/node_modules/webpack-dev-server/node_modules/bonjour/lib/mdns-server.js:54:17
    at Array.forEach (native)
    at Server._respondToQuery (/usr/local/lib/node_modules/webpack-dev-server/node_modules/bonjour/lib/mdns-server.js:48:19)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/node_modules/multicast-dns/index.js:45:40)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:544:8)
```
node 7.1.0
npm 5.2.0
webpack-dev-server 2.5.1
webpack 2.6.1

**Comment by r4fx** [comment]
check 2.6.0 release, it's fixed for me https://github.com/webpack/webpack-dev-server/pull/958

**Comment by hedrick** [comment]
Having this issue when using the bonjour npm package on an express app - kind of odd since webpack isn't included in the node_modules, package.json or the package-lock.json.

I know the npm bonjour package is included in webpack-dev-server but I'm not using this module.

**Comment by shellscape** [comment]
@hedrick please check the latest release. I believe we have this resolved. If it's still causing an issue for you, it might be worth following up with the bonjour team as I believe we're doing everything we can on our end.
