### ISSUE TITLE
BUG: Unhandled error with Node 8.1.4, on Win10 (Ubuntu for Windows)

### ISSUE THREAD

**Issue by darioshanghai** [webpack/webpack-dev-server#997]
With webpack 2.5.1, dev-server fails to start inside a Win10 install with Ubuntu for Windows (node is installed locally to Ubuntu).

```
webpack-dev-server --open

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EINVAL
    at exports._errnoException (util.js:1022:11)
    at Socket.addMembership (dgram.js:575:11)
    at Socket.<anonymous> (/mnt/c/Users/Dario/Desktop/dev/dario/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at startListening (dgram.js:144:10)
    at _handle.lookup (dgram.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! YARB@0.1.0 start: `webpack-dev-server --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the YARB@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dario/.npm/_logs/2017-07-18T01_03_50_655Z-debug.log`
```

```
more /home/dario/.npm/_logs/2017-07-18T01_03_50_655Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/dario/.nvm/versions/node/v8.1.4/bin/node',
1 verbose cli   '/home/dario/.nvm/versions/node/v8.1.4/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle YARB@0.1.0~prestart: YARB@0.1.0
6 silly lifecycle YARB@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle YARB@0.1.0~start: YARB@0.1.0
8 verbose lifecycle YARB@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle YARB@0.1.0~start: PATH: /home/dario/.nvm/versions/node/v8.1.4/lib/node_modules/npm/bin/node-gyp-b
in:/mnt/c/Users/Dario/Desktop/dev/dario/node_modules/.bin:/home/dario/.nvm/versions/node/v8.1.4/bin:/usr/local/sbin:/
usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/NVIDIA Corporation
/PhysX/Common:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/Syst
em32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files
(x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Component
s/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R)
Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/Wireless
Common:/mnt/c/Program Files (x86)/Calibre2:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Prog
ram Files (x86)/Yarn/bin:/mnt/c/Users/Dario/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Dario/AppData/Local/Yarn
/bin
10 verbose lifecycle YARB@0.1.0~start: CWD: /mnt/c/Users/Dario/Desktop/dev/dario
11 silly lifecycle YARB@0.1.0~start: Args: [ '-c', 'webpack-dev-server --open' ]
12 silly lifecycle YARB@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle YARB@0.1.0~start: Failed to exec start script
14 verbose stack Error: YARB@0.1.0 start: `webpack-dev-server --open`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/dario/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/util
s/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/dario/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/util
s/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid YARB@0.1.0
16 verbose cwd /mnt/c/Users/Dario/Desktop/dev/dario
17 verbose Linux 4.4.0-43-Microsoft
18 verbose argv "/home/dario/.nvm/versions/node/v8.1.4/bin/node" "/home/dario/.nvm/versions/node/v8.1.4/bin/npm" "sta
rt"
19 verbose node v8.1.4
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error YARB@0.1.0 start: `webpack-dev-server --open`
23 error Exit status 1
24 error Failed at the YARB@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by apai4** [comment]
I think this is fixed on master but the changes haven't been published to npm yet, see https://github.com/webpack/webpack-dev-server/issues/955 for a workaround until the maintainers release the next version

**Comment by Plazmaz** [comment]
Can confirm this is fixed on the latest branch or windows insider preview v16232(I think >16170 will work).

**Comment by shellscape** [comment]
Closing as changes have been published.
